-- AlterTable
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'OMR';
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "exchange_rate" DECIMAL(65,30) NOT NULL DEFAULT 1;
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "foreign_total" DECIMAL(65,30);
