#!/usr/bin/env bash
# BHD Pro — Cloud Agent install (idempotent baseline setup).
# Provisions Node 24, PostgreSQL 16, Redis, project dependencies and the
# backend .env. Safe to run repeatedly. Long-running servers live in the
# `terminals` config; per-boot service startup lives in start.sh.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

log() { printf '\n=== %s ===\n' "$1"; }

# ---------------------------------------------------------------------------
# Node 24 (project requires >=24). Installed via nvm so it wins over any
# older node earlier in PATH.
# ---------------------------------------------------------------------------
export NVM_DIR="$HOME/.nvm"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  log "Installing nvm"
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
fi
# shellcheck disable=SC1091
. "$NVM_DIR/nvm.sh"
if ! nvm ls 24 >/dev/null 2>&1; then
  log "Installing Node 24"
  nvm install 24
fi
nvm alias default 24 >/dev/null
nvm use 24 >/dev/null
NODE24_BIN="$(dirname "$(nvm which 24)")"
export PATH="$NODE24_BIN:$PATH"
node -v

# Ensure interactive agent shells also default to Node 24.
if ! grep -q "BHD Pro requires Node" "$HOME/.bashrc" 2>/dev/null; then
  cat >> "$HOME/.bashrc" <<'BASHRC'

# Use Node 24 (BHD Pro requires Node >=24)
__bhd_node24="$(ls -d "$HOME"/.nvm/versions/node/v24* 2>/dev/null | sort -V | tail -1)"
[ -n "$__bhd_node24" ] && export PATH="$__bhd_node24/bin:$PATH"
unset __bhd_node24
BASHRC
fi

# ---------------------------------------------------------------------------
# System services: PostgreSQL 16 + Redis (matches docker-compose.yml).
# ---------------------------------------------------------------------------
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  log "Installing PostgreSQL 16 + Redis"
  sudo apt-get update -y
  sudo apt-get install -y --no-install-recommends \
    postgresql-16 postgresql-client-16 redis-server openssl ca-certificates
fi

# ---------------------------------------------------------------------------
# Backend .env (generated once with random dev secrets; never committed).
# ---------------------------------------------------------------------------
if [ ! -f backend/.env ]; then
  log "Generating backend/.env"
  JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  JWT_REFRESH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  PAYMENT_SECRETS_KEY="$(openssl rand -base64 48 | tr -d '\n')"
  TOTP_SECRETS_KEY="$(openssl rand -base64 48 | tr -d '\n')"
  cat > backend/.env <<EOF
# Local development env for BHD Pro backend (generated by Cloud Agent setup).
NODE_ENV=development

DATABASE_URL=postgresql://qootk:qootk_secret@127.0.0.1:5432/qootk_pro?schema=public
DIRECT_URL=postgresql://qootk:qootk_secret@127.0.0.1:5432/qootk_pro?schema=public

JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
JWT_EXPIRATION=15m
JWT_REFRESH_EXPIRATION=7d

PAYMENT_SECRETS_KEY=$PAYMENT_SECRETS_KEY
PAYMENT_SECRETS_KEY_ID=pay-dev-1
PAYMENT_SECRETS_PREVIOUS_KEYS={}
TOTP_SECRETS_KEY=$TOTP_SECRETS_KEY
TOTP_SECRETS_KEY_ID=totp-dev-1
TOTP_SECRETS_PREVIOUS_KEYS={}

PLATFORM_ADMIN_EMAILS=admin@bhd.om
PLATFORM_OWNER_EMAIL=admin@bhd.om
ALLOW_PUBLIC_REGISTRATION=true
ALLOW_LEGACY_PUBLIC_INVOICE_IDS=false

REQUIRE_2FA_ROLES=off
REQUIRE_2FA_HARD_AFTER_GRACE=off

PORT=3001
TRUST_PROXY_HOPS=0
CORS_ORIGIN=http://localhost:3000
FRONTEND_URL=http://localhost:3000
API_PUBLIC_URL=http://localhost:3001
BACKEND_URL=http://localhost:3001
APP_URL=http://localhost:3000

WHATSAPP_ENABLED=false
EMAIL_ENABLED=false
EMAIL_MODE=mock
SMS_ENABLED=false
TWILIO_MODE=mock

ATTACHMENT_STORAGE=dataurl
ALLOW_INSECURE_DATAURL_STORAGE=true

REDIS_URL=redis://127.0.0.1:6379

SENTRY_ENABLED=false
NEXT_PUBLIC_SENTRY_ENABLED=false
EOF
fi

# ---------------------------------------------------------------------------
# Project dependencies.
# ---------------------------------------------------------------------------
log "Installing backend dependencies"
( cd backend && npm ci && npx prisma generate )

log "Installing frontend dependencies"
( cd frontend && npm ci )

log "install.sh complete"
