export const adminCopy = {
  ar: {
    brand: "حسابي",
    console: "لوحة تشغيل المنصة",
    overview: "المؤشرات",
    tenants: "الشركات",
    users: "المستخدمون",
    billing: "الاشتراكات والمدفوعات",
    plans: "الباقات والعروض",
    visits: "الزيارات",
    gateways: "بوابات الدفع",
    backApp: "تطبيق الشركة",
    search: "بحث…",
    save: "حفظ",
    active: "نشط",
    inactive: "موقوف",
    plan: "الباقة",
    started: "بداية الاشتراك",
    expires: "انتهاء الاشتراك",
    usersLimit: "حد المستخدمين",
    invoicesLimit: "حد الفواتير/شهر",
    unlimited: "بلا حد",
    details: "التفاصيل",
    payments: "المدفوعات",
    lastIp: "آخر IP",
    company: "الشركة",
    role: "الدور",
    email: "البريد",
    phone: "الهاتف",
    location: "الموقع",
    created: "تاريخ الإنشاء",
    sessions: "الجلسات",
    audit: "سجل النشاط",
    amount: "المبلغ",
    status: "الحالة",
    gateway: "البوابة",
    loading: "جارٍ التحميل…",
    empty: "لا توجد بيانات",
    overviewHint: "نظرة تشغيلية على المنصة بالكامل",
    tenantsHint: "إدارة الشركات والحدود والاشتراكات",
    usersHint: "كل المستخدمين مع الشركة والدفعات والـ IP",
    billingHint: "مدفوعات اشتراك كل شركة مع التواريخ",
    lang: "EN",
  },
  en: {
    brand: "Hisaby",
    console: "Platform operations",
    overview: "Overview",
    tenants: "Companies",
    users: "Users",
    billing: "Subscriptions & payments",
    plans: "Plans & offers",
    visits: "Visits",
    gateways: "Payment gateways",
    backApp: "Company app",
    search: "Search…",
    save: "Save",
    active: "Active",
    inactive: "Inactive",
    plan: "Plan",
    started: "Subscription start",
    expires: "Subscription end",
    usersLimit: "Users limit",
    invoicesLimit: "Invoices / month",
    unlimited: "Unlimited",
    details: "Details",
    payments: "Payments",
    lastIp: "Last IP",
    company: "Company",
    role: "Role",
    email: "Email",
    phone: "Phone",
    location: "Location",
    created: "Created",
    sessions: "Sessions",
    audit: "Activity",
    amount: "Amount",
    status: "Status",
    gateway: "Gateway",
    loading: "Loading…",
    empty: "No data yet",
    overviewHint: "Full platform operations snapshot",
    tenantsHint: "Manage companies, limits, and subscriptions",
    usersHint: "All users with company, payments, and IP",
    billingHint: "Subscription payments with dates per company",
    lang: "ع",
  },
} as const;

export type AdminLocale = keyof typeof adminCopy;
