export type LandingLocale = "ar" | "en";

export const landingCopy = {
  ar: {
    brand: "حسابي",
    brandEn: "Hisaby",
    navFeatures: "المزايا",
    navPricing: "الباقات",
    navCompany: "الشركة",
    login: "تسجيل الدخول",
    register: "ابدأ مجاناً",
    dashboard: "لوحة التحكم",
    headline: "محاسبة سحابية واضحة لأعمال الخليج والمنطقة",
    subhead:
      "فواتير، مخزون، ضريبة، وتقارير مالية من منصة واحدة — عربية أولاً، سريعة، وجاهزة للنمو.",
    trustLine: "يشغّله فريق شركة بن حمود للتطوير",
    featuresTitle: "كل ما تحتاجه لإدارة أعمالك",
    featuresSub: "واجهة واضحة تغطي المحاسبة اليومية دون تعقيد.",
    features: [
      {
        title: "الفوترة وعروض الأسعار",
        body: "أنشئ فواتير وإيصالات وعروض أسعار بعلامتك التجارية ورمز تحقق QR.",
      },
      {
        title: "المخزون والمشتريات",
        body: "تابع المنتجات والموردين وأوامر الشراء من مكان واحد.",
      },
      {
        title: "الضريبة والتقارير",
        body: "تقارير مالية وضريبة قيمة مضافة جاهزة لمتابعة أداء شركتك.",
      },
      {
        title: "فريق وصلاحيات",
        body: "أضف مستخدمين بأدوار مختلفة وتحكم بما يراه كل عضو.",
      },
      {
        title: "اشتراك مرن",
        body: "باقات تناسب الشركات الناشئة والمتوسطة مع ترقية عند الحاجة.",
      },
      {
        title: "دخول آمن",
        body: "تسجيل بكلمة مرور أو Google، مع حماية إضافية للحسابات الإدارية.",
      },
    ],
    pricingTitle: "باقات واضحة تبدأ من الريال العماني",
    pricingSub: "ابدأ صغيرًا ووسّع عندما ينمو عملك عبر المنطقة.",
    plans: [
      { name: "بدائية", price: "5", unit: "ر.ع / شهر", note: "للأعمال الصغيرة" },
      { name: "محترفة", price: "15", unit: "ر.ع / شهر", note: "الأكثر اختيارًا", featured: true },
      { name: "مؤسسية", price: "35", unit: "ر.ع / شهر", note: "بلا حدود عملية" },
    ],
    companyTitle: "الشركة المالكة والمشغّلة",
    companyName: "شركة بن حمود للتطوير",
    companyNameEn: "Bin Hamood Development",
    companyBody:
      "حسابي (Hisaby) منتج سحابي مطوّر ومشغّل بواسطة شركة بن حمود للتطوير — شركة تقنية من مسقط تبني أدوات عملية لأصحاب الأعمال في الخليج والمنطقة.",
    companyCta: "تعرّف على المنتج وابدأ تجربتك",
    footerTag: "محاسبة سحابية بسيطة وموثوقة",
    footerRights: "جميع الحقوق محفوظة",
    langSwitch: "English",
    adminLogin: "دخول الإدارة",
    regionLine: "عربي أولاً · ضريبة القيمة المضافة · جاهز لأعمال المنطقة",
    craftTitle: "من مسقط… للمنطقة",
    craftBody:
      "منصة عصرية بهوية هادئة مستوحاة من عُمان، مصمّمة لتخدم أعمالك في الخليج وما حوله.",
    chooseTitle: "اختر نظامك",
    chooseSub: "منصتان منفصلتان — محاسبة وكاشير — مع ربط اختياري عبر تسجيل الدخول أو مفتاح تقني",
    accountingCard: "حسابي للمحاسبة",
    accountingDesc: "فواتير، مخزون، تقارير، وضريبة القيمة المضافة",
    posCard: "حسابي للكاشير",
    posDesc: "بيع سريع، باركود، وخصم مخزون فوري للمحلات والمتاجر",
    openAccounting: "فتح المحاسبة",
    openPos: "فتح الكاشير",
    statsTitle: "المنصة بالأرقام",
    statsSub: "مؤشرات حية من بيانات المنصة — تتحدّث باستمرار مع نمو الأعمال.",
    statCompanies: "شركة نشطة",
    statUsers: "مستخدم",
    statVolume: "حجم العمليات المُدارة",
    statCollected: "تحصيلات",
    statReceivable: "قابل للتحصيل",
    statVisits: "زيارة للموقع",
    statVisits30: "آخر 30 يوماً",
  },
  en: {
    brand: "Hisaby",
    brandEn: "حسابي",
    navFeatures: "Features",
    navPricing: "Plans",
    navCompany: "Company",
    login: "Sign in",
    register: "Start free",
    dashboard: "Dashboard",
    headline: "Clear cloud accounting for Gulf & regional businesses",
    subhead:
      "Invoices, inventory, VAT, and financial reports in one fast Arabic-first platform — ready to grow with you.",
    trustLine: "Built and operated by Bin Hamood Development",
    featuresTitle: "Everything you need to run the books",
    featuresSub: "A clear interface for daily accounting — without the clutter.",
    features: [
      {
        title: "Invoicing & quotes",
        body: "Create branded invoices, receipts, and quotations with verification QR codes.",
      },
      {
        title: "Inventory & purchasing",
        body: "Track products, suppliers, and purchase orders in one place.",
      },
      {
        title: "VAT & reports",
        body: "Financial and VAT reports ready to monitor your company performance.",
      },
      {
        title: "Team & roles",
        body: "Invite users with roles so each person sees only what they need.",
      },
      {
        title: "Flexible plans",
        body: "Starter to enterprise packages priced in OMR — upgrade when you grow.",
      },
      {
        title: "Secure access",
        body: "Sign in with password or Google, with stronger protection for admins.",
      },
    ],
    pricingTitle: "Simple plans starting in OMR",
    pricingSub: "Start small. Scale as your business grows across the region.",
    plans: [
      { name: "Starter", price: "5", unit: "OMR / mo", note: "For small teams" },
      { name: "Professional", price: "15", unit: "OMR / mo", note: "Most popular", featured: true },
      { name: "Enterprise", price: "35", unit: "OMR / mo", note: "For growing orgs" },
    ],
    companyTitle: "Owner & operator",
    companyName: "Bin Hamood Development",
    companyNameEn: "شركة بن حمود للتطوير",
    companyBody:
      "Hisaby is designed, built, and operated by Bin Hamood Development — a Muscat-based technology company building practical tools for businesses across the Gulf and the wider region.",
    companyCta: "Explore the product and start today",
    footerTag: "Simple, reliable cloud accounting",
    footerRights: "All rights reserved",
    langSwitch: "العربية",
    adminLogin: "Admin sign-in",
    regionLine: "Arabic-first · VAT-ready · Built for regional business",
    craftTitle: "From Muscat to the region",
    craftBody:
      "A modern platform with a quiet Omani-inspired identity — built to serve businesses across the Gulf and beyond.",
    chooseTitle: "Choose your system",
    chooseSub: "Two separate products — accounting and POS — optionally linked via login or a technical key",
    accountingCard: "Hisaby Accounting",
    accountingDesc: "Invoices, inventory, reports, and VAT",
    posCard: "Hisaby POS",
    posDesc: "Fast checkout, barcodes, and instant stock for retail stores",
    openAccounting: "Open Accounting",
    openPos: "Open POS",
    statsTitle: "Platform at a glance",
    statsSub: "Live metrics from real platform data — growing with every business.",
    statCompanies: "Active companies",
    statUsers: "Users",
    statVolume: "Volume managed",
    statCollected: "Collected",
    statReceivable: "Receivable",
    statVisits: "Site visits",
    statVisits30: "Last 30 days",
  },
} as const;
