export type LandingLocale = "ar" | "en";

export const landingCopy = {
  ar: {
    brand: "حسابي",
    brandEn: "Hisaby",
    navFeatures: "الخدمات",
    navPricing: "الباقات",
    navCompany: "الشركة",
    navProducts: "الأنظمة",
    login: "تسجيل الدخول",
    register: "ابدأ مجاناً",
    dashboard: "لوحة التحكم",
    headline: "محاسبة سحابية واضحة لأعمال الخليج والمنطقة",
    subhead:
      "فواتير، كاشير، مطاعم، مخزون، ضريبة، وتقارير مالية من منصة واحدة — عربية أولاً، سريعة، وجاهزة للنمو.",
    trustLine: "يشغّله فريق شركة بن حمود للتطوير",
    featuresTitle: "خدمات مصمّمة لنمو أعمالك",
    featuresSub: "من الفوترة إلى الكاشير والمطاعم والتقارير — كل ما تحتاجه في تجربة واضحة وموثوقة.",
    features: [
      {
        title: "الفوترة وعروض الأسعار",
        body: "فواتير وإيصالات وعروض أسعار بشعارك وألوانك ورمز تحقق QR للموثوقية.",
      },
      {
        title: "حسابي للكاشير (POS)",
        body: "بيع سريع بالباركود، خصم مخزون فوري، وإيصالات جاهزة للمحلات والمتاجر.",
      },
      {
        title: "حسابي للمطاعم",
        body: "صالة وقائمة مربوطة بمنتجات شركتك — مع مسار للمطبخ والطلبات في الموجات التالية.",
      },
      {
        title: "المخزون والمستودعات",
        body: "تتبع الكميات حسب المستودع، أوامر الشراء، والجرد بدقة من مكان واحد.",
      },
      {
        title: "الضريبة والتقارير",
        body: "تقارير مالية وضريبة قيمة مضافة جاهزة لمتابعة الأداء والامتثال.",
      },
      {
        title: "أمان ومرونة الاشتراك",
        body: "دخول آمن، أدوار متعددة، وباقات تبدأ صغيراً وتتوسع مع نموك.",
      },
    ],
    pricingTitle: "باقات واضحة تبدأ من الريال العماني",
    pricingSub: "ابدأ صغيرًا ووسّع عندما ينمو عملك عبر المنطقة.",
    billingMonthly: "شهري",
    billingYearly: "سنوي",
    comparePlans: "مقارنة",
    hideCompare: "إخفاء المقارنة",
    compareTitle: "مقارنة الباقات",
    compareSub: "الفوارق بين الباقات — ما يتغيّر من باقة لأخرى",
    compareDiffsOnly: "الفوارق فقط",
    compareShowAll: "عرض الكل",
    compareFeature: "الميزة",
    comparePrice: "السعر",
    compareIncluded: "مشمولة",
    compareNotIncluded: "غير مشمولة",
    compareNeedTwo: "يلزم باقتان على الأقل للمقارنة",
    compareBilling: "استعراض الشهري والسنوي",
    perMonth: "ر.ع / شهر",
    perYear: "ر.ع / سنة",
    saveYearly: "وفّر",
    equivMonth: "يعادل",
    planDetails: "تفاصيل الباقة والخدمات",
    hideDetails: "إخفاء التفاصيل",
    showDetails: "عرض التفاصيل",
    includedServices: "الخدمات المشمولة",
    usersCap: "المستخدمون",
    invoicesCap: "الفواتير / شهر",
    supportLabel: "الدعم",
    unlimited: "بلا حدود",
    clickPlanHint: "اضغط على الباقة لعرض كل الخدمات والصلاحيات",
    plans: [
      { name: "بدائية", price: "2", unit: "ر.ع / شهر", note: "للأعمال الصغيرة" },
      { name: "محترفة", price: "10", unit: "ر.ع / شهر", note: "الأكثر اختيارًا", featured: true },
      { name: "مؤسسية", price: "35", unit: "ر.ع / شهر", note: "بلا حدود عملية" },
    ],
    companyTitle: "الشركة المالكة والمشغّلة",
    companyName: "شركة بن حمود للتطوير",
    companyNameEn: "Bin Hamood Development",
    companyBody:
      "حسابي (Hisaby) منتج سحابي مطوّر ومشغّل بواسطة شركة بن حمود للتطوير — شركة تقنية من مسقط تبني أدوات عملية لأصحاب الأعمال في الخليج والمنطقة.",
    companyCta: "تعرّف على المنتج وابدأ تجربتك",
    footerTag: "محاسبة سحابية بسيطة وموثوقة",
    footerRights: "جميع الحقوق محفوظة",
    langSwitch: "English",
    adminLogin: "دخول الإدارة",
    regionLine: "عربي أولاً · ضريبة القيمة المضافة · جاهز لأعمال المنطقة",
    craftTitle: "من مسقط… للمنطقة",
    craftBody:
      "منصة عصرية بهوية هادئة مستوحاة من عُمان، مصمّمة لتخدم أعمالك في الخليج وما حوله.",
    chooseTitle: "اختر نظامك",
    chooseSub: "محاسبة وكاشير ومطاعم — مع ربط اختياري عبر الحساب أو مفتاح تقني",
    accountingCard: "حسابي للمحاسبة",
    accountingDesc: "فواتير، مخزون، فروع، تقارير، وضريبة القيمة المضافة في لوحة واحدة",
    posCard: "حسابي للكاشير",
    posDesc: "بيع سريع، باركود، مخزون حسب المستودع، وإعادة طباعة الإيصالات",
    restoCard: "حسابي للمطاعم",
    restoDesc: "صالة وقائمة مربوطة بمنتجات شركتك — مطبخ وطلبات في الموجات التالية",
    openAccounting: "فتح المحاسبة",
    openPos: "فتح الكاشير",
    openResto: "فتح المطاعم",
    statsTitle: "المنصة بالأرقام",
    statsSub: "مؤشرات حية موحّدة بالريال العماني — مع نمو شهري وزوار فريدين.",
    customersTitle: "شركات تثق بحسابي",
    customersSub: "شعارات المشتركين المدفوعين — الباقة الأعلى أولاً ثم الأدنى، وتظهر تلقائياً بعد الدفع ورفع الشعار.",
    customersEmpty: "قريباً — انضم للشركات التي تدير أعمالها على حسابي.",
    statCompanies: "شركة نشطة",
    statUsers: "مستخدم",
    statVolume: "حجم العمليات (ر.ع)",
    statCollected: "تحصيلات (ر.ع)",
    statReceivable: "قابل للتحصيل (ر.ع)",
    statVisits: "زيارة للموقع",
    statUnique: "زائر فريد",
    statVisits30: "آخر 30 يوماً",
    growthLabel: "نمو",
    vsLastMonth: "مقارنة بالشهر السابق",
  },
  en: {
    brand: "Hisaby",
    brandEn: "حسابي",
    navFeatures: "Services",
    navPricing: "Plans",
    navCompany: "Company",
    navProducts: "Systems",
    login: "Sign in",
    register: "Start free",
    dashboard: "Dashboard",
    headline: "Clear cloud accounting for Gulf & regional businesses",
    subhead:
      "Invoices, POS, restaurants, inventory, VAT, and reports in one fast Arabic-first platform — ready to grow with you.",
    trustLine: "Built and operated by Bin Hamood Development",
    featuresTitle: "Services built for growing businesses",
    featuresSub: "From invoicing to POS, restaurants, and reports — everything you need in a clear, reliable experience.",
    features: [
      {
        title: "Invoicing & quotes",
        body: "Branded invoices, receipts, and quotations with verification QR codes.",
      },
      {
        title: "Hisaby POS",
        body: "Fast barcode checkout, instant stock deduction, and store-ready receipts.",
      },
      {
        title: "Hisaby Restaurants",
        body: "Floor and menu from your products — kitchen and tickets in upcoming waves.",
      },
      {
        title: "Inventory & warehouses",
        body: "Track quantities by warehouse, purchasing, and stock counts in one place.",
      },
      {
        title: "VAT & reports",
        body: "Financial and VAT reports ready to monitor performance and compliance.",
      },
      {
        title: "Secure, flexible plans",
        body: "Secure access, multi-role users, and plans that scale as you grow.",
      },
    ],
    pricingTitle: "Simple plans starting in OMR",
    pricingSub: "Start small. Scale as your business grows across the region.",
    billingMonthly: "Monthly",
    billingYearly: "Yearly",
    comparePlans: "Compare",
    hideCompare: "Hide compare",
    compareTitle: "Compare plans",
    compareSub: "See what differs between packages",
    compareDiffsOnly: "Differences only",
    compareShowAll: "Show all",
    compareFeature: "Feature",
    comparePrice: "Price",
    compareIncluded: "Included",
    compareNotIncluded: "Not included",
    compareNeedTwo: "At least two plans are needed to compare",
    compareBilling: "Compare monthly & yearly",
    perMonth: "OMR / mo",
    perYear: "OMR / yr",
    saveYearly: "Save",
    equivMonth: "equals",
    planDetails: "Plan details & services",
    hideDetails: "Hide details",
    showDetails: "Show details",
    includedServices: "Included services",
    usersCap: "Users",
    invoicesCap: "Invoices / mo",
    supportLabel: "Support",
    unlimited: "Unlimited",
    clickPlanHint: "Tap a plan to see every included service and permission",
    plans: [
      { name: "Starter", price: "2", unit: "OMR / mo", note: "For small teams" },
      { name: "Professional", price: "10", unit: "OMR / mo", note: "Most popular", featured: true },
      { name: "Enterprise", price: "35", unit: "OMR / mo", note: "For growing orgs" },
    ],
    companyTitle: "Owner & operator",
    companyName: "Bin Hamood Development",
    companyNameEn: "شركة بن حمود للتطوير",
    companyBody:
      "Hisaby is designed, built, and operated by Bin Hamood Development — a Muscat-based technology company building practical tools for businesses across the Gulf and the wider region.",
    companyCta: "Explore the product and start today",
    footerTag: "Simple, reliable cloud accounting",
    footerRights: "All rights reserved",
    langSwitch: "العربية",
    adminLogin: "Admin sign-in",
    regionLine: "Arabic-first · VAT-ready · Built for regional business",
    craftTitle: "From Muscat to the region",
    craftBody:
      "A modern platform with a quiet Omani-inspired identity — built to serve businesses across the Gulf and beyond.",
    chooseTitle: "Choose your system",
    chooseSub: "Accounting, retail POS, and restaurants — optionally linked via account or key",
    accountingCard: "Hisaby Accounting",
    accountingDesc: "Invoices, inventory, branches, reports, and VAT in one dashboard",
    posCard: "Hisaby POS",
    posDesc: "Fast checkout, barcodes, warehouse stock, and receipt reprints",
    restoCard: "Hisaby Restaurants",
    restoDesc: "Floor and menu from your products — kitchen and tickets in later waves",
    openAccounting: "Open Accounting",
    openPos: "Open POS",
    openResto: "Open Restaurants",
    statsTitle: "Platform at a glance",
    statsSub: "Live metrics normalized to OMR — with monthly growth and unique visitors.",
    customersTitle: "Businesses that trust Hisaby",
    customersSub: "Paid subscribers — highest plan first, then lower tiers; appear after checkout and logo upload.",
    customersEmpty: "Coming soon — join businesses running on Hisaby.",
    statCompanies: "Active companies",
    statUsers: "Users",
    statVolume: "Volume managed (OMR)",
    statCollected: "Collected (OMR)",
    statReceivable: "Receivable (OMR)",
    statVisits: "Site visits",
    statUnique: "Unique visitors",
    statVisits30: "Last 30 days",
    growthLabel: "Growth",
    vsLastMonth: "vs previous month",
  },
} as const;
