export type PosLocale = "ar" | "en";

export const posCopy = {
  ar: {
    brand: "كاشير حسابي",
    brandEn: "Hisaby POS",
    tagline: "نقطة بيع عالمية للمحلات والمتاجر",
    loginTitle: "دخول الكاشير",
    loginSub: "سجّل الدخول لفتح شاشة البيع",
    email: "البريد",
    password: "كلمة المرور",
    signIn: "دخول",
    toAccounting: "المحاسبة",
    toPos: "الكاشير",
    settings: "الإعدادات والربط",
    logout: "خروج",
    scanPlaceholder: "امسح الباركود أو اكتب SKU ثم Enter",
    searchPlaceholder: "بحث سريع عن منتج…",
    cart: "السلة",
    emptyCart: "السلة فارغة — ابدأ بالمسح",
    qty: "الكمية",
    price: "السعر",
    total: "الإجمالي",
    subtotal: "المجموع",
    tax: "الضريبة",
    payCash: "نقدًا",
    payCard: "بطاقة",
    clear: "تفريغ",
    stock: "المخزون",
    linked: "النظامان مربوطان",
    unlinked:
      "النظامان غير مربوطين — سجّل الدخول بنفس حساب المحاسبة أو فعّل الربط من الإعدادات",
    activateLink: "ربط عبر تسجيل الدخول",
    generateKey: "إنشاء مفتاح تقني",
    pasteKey: "لصق مفتاح الربط",
    saveKey: "تأكيد الربط",
    keyHint: "احفظ المفتاح الآن — لن يظهر مرة أخرى",
    saleOk: "تم البيع بنجاح",
    saleFail: "فشل إتمام البيع",
    notFound: "لا يوجد منتج بهذا الرمز",
    printReceipt: "طباعة إيصال",
    openPos: "فتح الكاشير",
    openAccounting: "فتح المحاسبة",
    chooseProduct: "اختر نظامك",
    chooseSub: "منصتان منفصلتان — محاسبية وكاشير — مع ربط اختياري",
    accountingCard: "حسابي للمحاسبة",
    accountingDesc: "فواتير، مخزون، تقارير، وضريبة القيمة المضافة",
    posCard: "حسابي للكاشير",
    posDesc: "بيع سريع، باركود، وخصم مخزون فوري للمحلات",
    emptyCatalog: "لا توجد منتجات للبيع بعد",
    emptyCatalogHint: "أضف منتجات من المخزون ثم ارجع للكاشير — يُفضّل تعبئة الباركود لكل صنف",
    goInventory: "الذهاب للمخزون",
    barcodeHint: "ضع المؤشر هنا وامسح بالقارئ — يعمل مع الباركود أو رمز SKU",
    inventory: "المخزون",
    posLinkTitle: "ربط حسابي للكاشير",
    posLinkDesc: "فعّل الربط أو أنشئ مفتاحاً تقنياً لربط الكاشير بالمحاسبة",
  },
  en: {
    brand: "Hisaby POS",
    brandEn: "كاشير حسابي",
    tagline: "World-class point of sale for retail stores",
    loginTitle: "POS sign in",
    loginSub: "Sign in to open the checkout floor",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    toAccounting: "Accounting",
    toPos: "POS",
    settings: "Settings & link",
    logout: "Sign out",
    scanPlaceholder: "Scan barcode or type SKU, then Enter",
    searchPlaceholder: "Quick product search…",
    cart: "Cart",
    emptyCart: "Cart is empty — start scanning",
    qty: "Qty",
    price: "Price",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    payCash: "Cash",
    payCard: "Card",
    clear: "Clear",
    stock: "Stock",
    linked: "Apps are linked",
    unlinked:
      "Apps are not linked — sign in with the same accounting account or enable linking in settings",
    activateLink: "Link via shared login",
    generateKey: "Generate technical key",
    pasteKey: "Paste integration key",
    saveKey: "Confirm link",
    keyHint: "Store this key now — it will not be shown again",
    saleOk: "Sale completed",
    saleFail: "Sale failed",
    notFound: "No product for this code",
    printReceipt: "Print receipt",
    openPos: "Open POS",
    openAccounting: "Open Accounting",
    chooseProduct: "Choose your system",
    chooseSub: "Two separate products — accounting and POS — with optional linking",
    accountingCard: "Hisaby Accounting",
    accountingDesc: "Invoices, inventory, reports, and VAT",
    posCard: "Hisaby POS",
    posDesc: "Fast checkout, barcodes, and instant stock for stores",
    emptyCatalog: "No products to sell yet",
    emptyCatalogHint: "Add products in Inventory, then return here — barcodes make scanning fastest",
    goInventory: "Go to inventory",
    barcodeHint: "Keep focus here and scan — accepts barcode or SKU",
    inventory: "Inventory",
    posLinkTitle: "Hisaby POS link",
    posLinkDesc: "Activate linking or generate a technical key to connect POS with Accounting",
  },
} as const;
