export type PosLocale = "ar" | "en";

export const posCopy = {
  ar: {
    brand: "كاشير حسابي",
    brandEn: "Hisaby POS",
    tagline: "نقطة بيع عالمية للمحلات والمتاجر",
    loginTitle: "دخول الكاشير",
    loginSub: "سجّل الدخول لفتح شاشة البيع",
    email: "البريد",
    password: "كلمة المرور",
    signIn: "دخول",
    toAccounting: "المحاسبة",
    toPos: "الكاشير",
    settings: "الإعدادات والربط",
    logout: "خروج",
    scanPlaceholder: "امسح الباركود أو اكتب SKU ثم Enter",
    searchPlaceholder: "بحث سريع عن منتج…",
    cart: "السلة",
    emptyCart: "السلة فارغة — ابدأ بالمسح",
    qty: "الكمية",
    price: "السعر",
    total: "الإجمالي",
    subtotal: "المجموع",
    tax: "الضريبة",
    payCash: "نقدًا",
    payCard: "بطاقة",
    payBank: "تحويل بنكي",
    payStoreCredit: "رصيد متجر",
    storeCreditNeedCustomer: "اختر عميلاً لاستخدام رصيد المتجر",
    storeCreditLow: "رصيد المتجر غير كافٍ",
    storeCreditOffline: "رصيد المتجر يتطلب اتصالاً بالشبكة",
    refundMethod: "طريقة الاسترداد",
    refundOriginal: "نفس طريقة البيع",
    refundCash: "نقداً",
    refundStoreCredit: "رصيد متجر",
    amountTendered: "المبلغ المستلم",
    changeDue: "الباقي",
    confirmCash: "تأكيد النقد",
    findReceipt: "بحث برقم الإيصال",
    receiptNotFound: "لم يُعثر على الإيصال",
    catalogSynced: "تمت مزامنة الكتالوج أوفلاين",
    catalogSyncFail: "تعذرت مزامنة الكتالوج",
    creditBalance: "رصيد",
    clear: "تفريغ",
    parkCart: "تعليق",
    recallCart: "استرجاع",
    parkedCarts: "سلات معلّقة",
    parkOk: "تم تعليق السلة",
    parkFail: "فشل تعليق السلة",
    parkEmpty: "السلة فارغة",
    deleteParked: "حذف",
    parkName: "سلة معلّقة",
    stock: "المخزون",
    discount: "خصم",
    linked: "النظامان مربوطان",
    unlinked:
      "النظامان غير مربوطين — استخدم مخزون ودفاتر الكاشير، أو اربطهما للمحاسبة الكاملة",
    activateLink: "ربط عبر تسجيل الدخول",
    unlinkSystems: "فصل الربط (تجربة منفصلة)",
    unlinkOk: "تم فصل المحاسبة عن الكاشير",
    unlinkConfirm: "فصل الربط؟ يمكنك إعادة الربط لاحقاً من نفس الشاشة.",
    unlinkFail: "تعذر فصل الربط",
    generateKey: "إنشاء مفتاح تقني",
    pasteKey: "لصق مفتاح الربط",
    saveKey: "تأكيد الربط",
    keyHint: "احفظ المفتاح الآن — لن يظهر مرة أخرى",
    saleOk: "تم البيع بنجاح",
    saleFail: "فشل إتمام البيع",
    saleQueued: "البيع في طابور الأوفلاين — سيُزامَن عند عودة الشبكة",
    pendingOffline: "مبيعات بانتظار المزامنة",
    syncNow: "مزامنة",
    syncOk: "تمت مزامنة المبيعات الأوفلاين",
    syncFail: "تعذرت المزامنة — تحقق من الشبكة",
    thermalPrint: "طباعة حرارية",
    thermalFail: "الطابعة الحرارية غير متاحة — جرّب Web Serial أو الطباعة العادية",
    preferThermal: "تفضيل الطابعة الحرارية (Web Serial) — اختياري",
    varianceNeedApproval: "فارق النقد يتطلب موافقة مزدوجة",
    notFound: "لا يوجد منتج بهذا الرمز",
    printReceipt: "طباعة إيصال",
    openPos: "فتح الكاشير",
    openAccounting: "فتح المحاسبة",
    chooseProduct: "اختر نظامك",
    chooseSub: "منصتان منفصلتان — محاسبية وكاشير — مع ربط اختياري",
    accountingCard: "حسابي للمحاسبة",
    accountingDesc: "فواتير، مخزون، تقارير، وضريبة القيمة المضافة",
    posCard: "حسابي للكاشير",
    posDesc: "بيع سريع، باركود، وخصم مخزون فوري للمحلات",
    emptyCatalog: "لا توجد منتجات للبيع بعد",
    emptyCatalogHint: "أضف منتجات من المخزون ثم ارجع للكاشير — يُفضّل تعبئة الباركود لكل صنف",
    goInventory: "الذهاب للمخزون",
    barcodeHint: "ضع المؤشر هنا وامسح بالقارئ — يعمل مع الباركود أو رمز SKU",
    inventory: "المخزون",
    posInventoryTitle: "مخزون الكاشير",
    posInventorySub: "إدارة المنتجات والكميات داخل الكاشير دون مغادرة النظام",
    posBooksTitle: "دفاتر بسيطة",
    posBooksNav: "دفاتر",
    posBooksSub: "إيرادات المبيعات ومصاريف الصندوق لهذا الشهر — بدون محاسبة متقدمة",
    posBooksUpsellTitle: "هل تحتاج محاسبة كاملة؟",
    posBooksUpsellBody:
      "الكاشير المنفصل يكفي للمخزون والإيرادات والمصاريف. للفواتير الضريبية والتقارير المتقدمة والربط الكامل — اشترك في المحاسبة واربط النظامين من الإعدادات.",
    previewFullAccounting: "معاينة المحاسبة",
    addProduct: "إضافة منتج",
    editProduct: "تعديل منتج",
    productCol: "المنتج",
    productName: "اسم المنتج",
    category: "الفئة",
    unit: "الوحدة",
    costPrice: "التكلفة",
    salePrice: "سعر البيع",
    minQty: "الحد الأدنى",
    sku: "الرمز",
    barcode: "الباركود",
    productSaved: "تم حفظ المنتج",
    productSaveFail: "فشل حفظ المنتج",
    productNeedNameCat: "الاسم والفئة مطلوبان",
    codesLoadError: "تعذر توليد الرمز/الباركود",
    addCategoryNamed: "إضافة فئة «{name}»",
    addUnitNamed: "إضافة وحدة «{name}»",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    booksRevenue: "إيرادات الشهر",
    booksExpenses: "مصاريف الشهر",
    booksRefunds: "استردادات",
    booksVoids: "إلغاءات",
    booksNet: "الصافي",
    booksSales: "بيع",
    booksEntries: "قيد",
    recordExpense: "تسجيل مصروف",
    recordExpenseHint: "يُسجَّل كإخراج نقد من الوردية المفتوحة",
    expenseReason: "السبب",
    expenseReasonPh: "إيجار، كهرباء، مشتريات…",
    expenseDefaultReason: "مصروف كاشير",
    saveExpense: "حفظ المصروف",
    expenseSaved: "تم تسجيل المصروف",
    expenseFail: "تعذر تسجيل المصروف — تأكد من وجود وردية مفتوحة",
    expenseNeedAmount: "أدخل مبلغاً أكبر من صفر",
    amount: "المبلغ",
    recentRevenue: "آخر المبيعات",
    recentExpenses: "آخر المصاريف",
    noExpenses: "لا مصاريف بعد",
    refresh: "تحديث",
    posLinkTitle: "ربط حسابي للكاشير",
    posLinkDesc: "فعّل الربط أو أنشئ مفتاحاً تقنياً لربط الكاشير بالمحاسبة",
    warehouse: "المستودع",
    warehouseDefault: "المستودع",
    warehouseAll: "اختر مستودعاً",
    warehouseHint: "الرصيد المعروض لهذا المستودع فقط — اختر المستودع قبل البيع",
    clearConfirm: "تفريغ السلة؟",
    recentSales: "آخر المبيعات",
    reprint: "إعادة طباعة",
    noRecentSales: "لا مبيعات كاشير حديثة",
    escHint: "Esc لتفريغ السلة",
    adminOnlyKeys: "إنشاء وتأكيد المفتاح التقني متاح للمدير فقط",
    forbidden: "ليس لديك صلاحية لهذا الإجراء",
    linkFail: "فشل الربط — تحقق من الصلاحية أو المفتاح",
    voidSale: "إلغاء",
    voidConfirm: "إلغاء هذا البيع واسترجاع المخزون؟",
    voidOk: "تم إلغاء البيع",
    voidFail: "فشل إلغاء البيع",
    walkIn: "عميل نقدي",
    customer: "العميل",
    searchCustomer: "بحث بالاسم أو رقم الهاتف…",
    payment: "الدفع",
    recallOverwrite: "السلة الحالية غير فارغة — استبدالها بالسلة المعلّقة؟",
    scanCamera: "مسح بالكاميرا",
    scanCameraHint: "وجّه الكاميرا للباركود — أو استخدم قارئ الأجهزة / اكتب الرمز",
    cameraPermissionDenied: "تم رفض إذن الكاميرا",
    cameraUnsupported: "الكاميرا غير مدعومة على هذا الجهاز",
    approvals: "الموافقات",
    approvalsTitle: "طلبات الموافقة",
    approvalsHint: "موافقات الكاشير الحساسة — صالح 15 دقيقة",
    approvalsEmpty: "لا طلبات معلّقة",
    approvalsFail: "تعذر تحميل الموافقات",
    approvalsManagerOnly: "هذه الصفحة للمدير فقط",
    approve: "موافقة",
    reject: "رفض",
    approveOk: "تمت الموافقة",
    rejectOk: "تم الرفض",
    expiresAt: "ينتهي",
    shifts: "الوردية",
    shiftsTitle: "ورديات الصندوق",
    shiftsHint: "افتح وردية قبل البيع — أغلقها لتقرير Z",
    shiftOpen: "وردية مفتوحة",
    shiftClosed: "تم إغلاق الوردية",
    shiftClosedLabel: "مغلقة",
    shiftOpened: "تم فتح الوردية",
    shiftFail: "تعذر تنفيذ عملية الوردية",
    noOpenShift: "لا توجد وردية مفتوحة",
    openShift: "فتح وردية",
    closeShift: "إغلاق + تقرير Z",
    openingFloat: "عهدة افتتاح",
    closingCash: "نقد الإغلاق الفعلي",
    openedBy: "فتحها",
    shiftHistory: "سجل الورديات",
    noShiftHistory: "لا سجل بعد",
    zSales: "إجمالي المبيعات",
    zCash: "نقد",
    zExpected: "نقد متوقع",
    zRefunds: "استردادات",
    zVoids: "إلغاءات",
    zCount: "عدد العمليات",
    zVariance: "الفارق",
    cashSales: "نقد",
    cardSales: "بطاقة",
    expectedInDrawer: "متوقع بالصندوق",
    shortage: "نقص",
    overage: "زيادة",
    balanced: "متوازن",
    reconciliationTitle: "مطابقة الصندوق",
    countedCash: "النقد المعدود",
    difference: "الفرق",
    aiReview: "مراجعة ذكية",
    aiReviewOk: "لا مؤشرات شاذة",
    aiReviewFail: "تعذر تشغيل المراجعة الذكية",
    aiReviewTitle: "مراجعة الوردية",
    refundSale: "استرداد",
    refundOk: "تم الاسترداد",
    refundFail: "فشل الاسترداد",
    refundTitle: "استرداد جزئي",
    refundReason: "سبب الاسترداد",
    refundQty: "كمية الاسترداد",
    refundSelect: "اختر الأصناف والكميات",
    refundContinue: "متابعة للموافقة",
    printZReport: "طباعة تقرير Z",
    xReport: "تقرير X",
    printXReport: "طباعة تقرير X",
    xReportFail: "تعذر تحميل تقرير X",
    cashIn: "إدخال نقد",
    cashOut: "إخراج نقد",
    cashInOk: "تم إدخال النقد",
    cashOutOk: "تم إخراج النقد",
    cashMovementFail: "تعذر تسجيل حركة النقد",
    cashMovementAmount: "المبلغ",
    cashMovementReason: "السبب (اختياري)",
    cashMovementReasonRequired: "السبب (مطلوب للإخراج)",
    cashMovements: "حركات النقد",
    noCashMovements: "لا حركات نقد بعد",
    cashPostedToGl: "تم الترحيل إلى اليومية",
    shiftsTodayTitle: "ورديات اليوم",
    shiftsTodayHint: "جميع المستودعات — مبيعات ونقد متوقع",
    shiftsTodayEmpty: "لا ورديات اليوم",
    shiftStatusOpen: "مفتوحة",
    shiftStatusClosed: "مغلقة",
    stockExceedsBlock: "الكمية تتجاوز المخزون المتاح — عدّل السلة قبل الدفع",
    stockLowAfterSale: "بعد هذا البيع سينخفض المخزون تحت الحد الأدنى. المتابعة؟",
    zCashIn: "إدخال نقد",
    zCashOut: "إخراج نقد",
    shareReportWhatsApp: "مشاركة واتساب",
    shareReportEmail: "مشاركة بريد",
    recentPurchases: "مشتريات حديثة",
    noRecentPurchases: "لا مشتريات حديثة",
    addCustomer: "عميل جديد",
    customerName: "اسم العميل",
    customerPhone: "هاتف العميل",
    phoneRequired: "رقم الهاتف مطلوب",
    phoneCountryCode: "رمز الدولة",
    phoneLocal: "رقم الجوال",
    phonePreview: "المعاينة",
    customerEmail: "البريد (اختياري)",
    customerSaved: "تم حفظ العميل",
    catalogStale: "الكتالوج قديم — حدّث عند توفر الشبكة",
    refreshCatalog: "تحديث الكتالوج",
    lowStock: "مخزون منخفض",
    openDrawer: "فتح الدرج",
    preferCashDrawer: "فتح درج النقد تلقائياً بعد الدفع النقدي",
    todaySales: "مبيعات اليوم",
    shiftStripOpen: "وردية مفتوحة",
    shiftStripClosed: "لا وردية",
    requireOpenShift: "يتطلب وردية مفتوحة قبل البيع",
    requireOpenShiftToast: "افتح وردية قبل إتمام البيع",
    openShiftsLink: "فتح الورديات",
    shareWhatsApp: "مشاركة واتساب",
    shareEmail: "مشاركة بريد",
    shareWhatsAppPdfPreparing: "جاري تجهيز PDF للواتساب…",
    shareWhatsAppPdfOk: "تم إرسال الإيصال مع PDF",
    shareWhatsAppPdfDownloaded: "تم تنزيل PDF — أرفقه في واتساب",
    shareWhatsAppPdfFail: "تعذر إنشاء PDF للواتساب",
    partnerPay: "دفع شريك (بطاقة/محفظة)",
    partnerPayHint: "يفتح بوابة ثواني/Stripe/PayPal — ليس شارة NFC",
    partnerPayOpened: "تم فتح صفحة دفع الشريك",
    partnerPayFail: "تعذر فتح دفع الشريك — تأكد من تفعيل البوابة",
    partnerPayOffline: "دفع الشريك يتطلب فاتورة متصلة بالخادم",
    terminalTap: "لمس / Terminal",
    terminalTapHint: "SoftPOS أو طرف شريك — دفع العميل باللمس (ليس شارة الموافقة)",
    terminalTapOpened: "تم فتح جلسة اللمس / Terminal",
    terminalTapFail: "تعذر بدء جلسة Terminal — راجع البوابة أو POS_TERMINAL_MODE",
    terminalTapOffline: "Terminal يتطلب اتصالاً بالخادم",
    terminalTapMockOk: "تم تأكيد اللمس التجريبي (mock)",
    terminalTapPaid: "تم استلام دفع Terminal / الشريك",
    partnerPayPending: "فاتورة بانتظار الدفع — راقب اكتمال الجلسة",
    opQueued: "أُضيفت العملية لطابور الأوفلاين — ستُزامَن عند الاتصال",
    offlineOpLocalOnly: "لا يمكن إلغاء/استرداد إيصال أوفلاين محلي قبل المزامنة",
    muteScanBeep: "كتم صوت المسح",
    favorites: "المفضلة",
    pinFavorite: "تثبيت",
    unpinFavorite: "إلغاء التثبيت",
    renameParked: "إعادة تسمية",
    renameParkedPrompt: "اسم السلة المعلّقة",
    renameParkedOk: "تم تحديث الاسم",
    refundReasonDamaged: "تالف",
    refundReasonWrongItem: "صنف خاطئ",
    refundReasonCustomerReturn: "إرجاع عميل",
    refundReasonOther: "أخرى",
    shortcutsTitle: "اختصارات لوحة المفاتيح",
    shortcutEsc: "Esc — تفريغ السلة",
    shortcutScan: "Enter — مسح / إضافة من حقل الباركود",
    shortcutHelp: "? — عرض هذه المساعدة",
    keypadOk: "موافق",
    keypadClear: "مسح",
    tip: "بقشيش",
    tipPercent: "نسبة البقشيش",
    tipCustom: "مخصص",
    splitTender: "تقسيم الدفع",
    splitCash: "نقد",
    splitCard: "بطاقة",
    splitSumMismatch: "مجموع الدفعات يجب أن يساوي الإجمالي",
    splitCheckout: "إتمام التقسيم",
    parkNotes: "ملاحظات السلة",
    parkNotesPlaceholder: "ملاحظات اختيارية عند التعليق…",
    editParkNotes: "ملاحظات",
    commission: "عمولة",
    commissionRemaining: "متبقي",
    commissionPaid: "صُرف",
    commissionEarned: "مكتسب",
    commissionToday: "عمولة اليوم",
    payout: "صرف",
    payoutOk: "تم صرف العمولة",
    payoutFail: "فشل صرف العمولة",
    payoutAmount: "مبلغ الصرف",
    points: "نقاط",
    incentivesTitle: "العمولة ونقاط الولاء",
    incentivesDesc: "نسبة عمولة الكاشير ونقاط العملاء على المبيعات",
    incentivesSaved: "تم حفظ إعدادات الحوافز",
    cashierCommissionEnabled: "تفعيل عمولة الكاشير",
    cashierPercent: "نسبة العمولة %",
    customerLoyaltyEnabled: "تفعيل نقاط العملاء",
    pointsPerUnit: "نقاط لكل وحدة عملة",
    nextBonusTier: "الشريحة التالية",
    ledgerEmpty: "لا حركات بعد",
  },
  en: {
    brand: "Hisaby POS",
    brandEn: "كاشير حسابي",
    tagline: "World-class point of sale for retail stores",
    loginTitle: "POS sign in",
    loginSub: "Sign in to open the checkout floor",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    toAccounting: "Accounting",
    toPos: "POS",
    settings: "Settings & link",
    logout: "Sign out",
    scanPlaceholder: "Scan barcode or type SKU, then Enter",
    searchPlaceholder: "Quick product search…",
    cart: "Cart",
    emptyCart: "Cart is empty — start scanning",
    qty: "Qty",
    price: "Price",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    payCash: "Cash",
    payCard: "Card",
    payBank: "Bank transfer",
    payStoreCredit: "Store credit",
    storeCreditNeedCustomer: "Select a customer to use store credit",
    storeCreditLow: "Insufficient store credit",
    storeCreditOffline: "Store credit requires a network connection",
    refundMethod: "Refund destination",
    refundOriginal: "Original payment method",
    refundCash: "Cash",
    refundStoreCredit: "Store credit",
    amountTendered: "Amount tendered",
    changeDue: "Change due",
    confirmCash: "Confirm cash",
    findReceipt: "Find by receipt number",
    receiptNotFound: "Receipt not found",
    catalogSynced: "Offline catalog synced",
    catalogSyncFail: "Could not sync catalog",
    creditBalance: "Credit",
    clear: "Clear",
    parkCart: "Park",
    recallCart: "Recall",
    parkedCarts: "Parked carts",
    parkOk: "Cart parked",
    parkFail: "Could not park cart",
    parkEmpty: "Cart is empty",
    deleteParked: "Delete",
    parkName: "Parked cart",
    stock: "Stock",
    discount: "Discount",
    linked: "Apps are linked",
    unlinked:
      "Apps are not linked — you can test each system separately, or link them from settings",
    activateLink: "Link via shared login",
    unlinkSystems: "Unlink (test separately)",
    unlinkOk: "Accounting and POS unlinked",
    unlinkConfirm: "Unlink the apps? You can link them again later from this screen.",
    unlinkFail: "Could not unlink",
    generateKey: "Generate technical key",
    pasteKey: "Paste integration key",
    saveKey: "Confirm link",
    keyHint: "Store this key now — it will not be shown again",
    saleOk: "Sale completed",
    saleFail: "Sale failed",
    saleQueued: "Sale queued offline — will sync when back online",
    pendingOffline: "Pending offline sales",
    syncNow: "Sync",
    syncOk: "Offline sales synced",
    syncFail: "Sync failed — check the network",
    thermalPrint: "Thermal print",
    thermalFail: "Thermal printer unavailable — try Web Serial or browser print",
    preferThermal: "Prefer thermal printer (Web Serial) — optional",
    varianceNeedApproval: "Cash variance needs dual-control approval",
    notFound: "No product for this code",
    printReceipt: "Print receipt",
    openPos: "Open POS",
    openAccounting: "Open Accounting",
    chooseProduct: "Choose your system",
    chooseSub: "Two separate products — accounting and POS — with optional linking",
    accountingCard: "Hisaby Accounting",
    accountingDesc: "Invoices, inventory, reports, and VAT",
    posCard: "Hisaby POS",
    posDesc: "Fast checkout, barcodes, and instant stock for stores",
    emptyCatalog: "No products to sell yet",
    emptyCatalogHint: "Add products in Inventory, then return here — barcodes make scanning fastest",
    goInventory: "Go to inventory",
    barcodeHint: "Keep focus here and scan — accepts barcode or SKU",
    inventory: "Inventory",
    posInventoryTitle: "POS inventory",
    posInventorySub: "Manage products and stock inside POS without leaving the cashier app",
    posBooksTitle: "Simple books",
    posBooksNav: "Books",
    posBooksSub: "Sales revenue and drawer expenses for this month — no advanced accounting",
    posBooksUpsellTitle: "Need full accounting?",
    posBooksUpsellBody:
      "Standalone POS covers inventory, revenue, and expenses. For tax invoices, advanced reports, and full linking — subscribe to Accounting and connect the apps from settings.",
    previewFullAccounting: "Preview accounting",
    addProduct: "Add product",
    editProduct: "Edit product",
    productCol: "Product",
    productName: "Product name",
    category: "Category",
    unit: "Unit",
    costPrice: "Cost",
    salePrice: "Sale price",
    minQty: "Min qty",
    sku: "SKU",
    barcode: "Barcode",
    productSaved: "Product saved",
    productSaveFail: "Could not save product",
    productNeedNameCat: "Name and category are required",
    codesLoadError: "Could not generate SKU/barcode",
    addCategoryNamed: "Add category “{name}”",
    addUnitNamed: "Add unit “{name}”",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    booksRevenue: "Month revenue",
    booksExpenses: "Month expenses",
    booksRefunds: "Refunds",
    booksVoids: "Voids",
    booksNet: "Net",
    booksSales: "sales",
    booksEntries: "entries",
    recordExpense: "Record expense",
    recordExpenseHint: "Saved as cash-out on the open shift",
    expenseReason: "Reason",
    expenseReasonPh: "Rent, utilities, supplies…",
    expenseDefaultReason: "POS expense",
    saveExpense: "Save expense",
    expenseSaved: "Expense recorded",
    expenseFail: "Could not record expense — open a shift first",
    expenseNeedAmount: "Enter an amount greater than zero",
    amount: "Amount",
    recentRevenue: "Recent sales",
    recentExpenses: "Recent expenses",
    noExpenses: "No expenses yet",
    refresh: "Refresh",
    posLinkTitle: "Hisaby POS link",
    posLinkDesc: "Activate linking or generate a technical key to connect POS with Accounting",
    warehouse: "Warehouse",
    warehouseDefault: "Warehouse",
    warehouseAll: "Select warehouse",
    warehouseHint: "Shown stock is for the selected warehouse only — pick a warehouse before selling",
    clearConfirm: "Clear the cart?",
    recentSales: "Recent sales",
    reprint: "Reprint",
    noRecentSales: "No recent POS sales",
    escHint: "Esc clears cart",
    adminOnlyKeys: "Only admins can generate or confirm the technical key",
    forbidden: "You do not have permission for this action",
    linkFail: "Link failed — check permissions or the key",
    voidSale: "Void",
    voidConfirm: "Void this sale and restore stock?",
    voidOk: "Sale voided",
    voidFail: "Could not void sale",
    walkIn: "Walk-in",
    customer: "Customer",
    searchCustomer: "Search by name or phone…",
    payment: "Payment",
    recallOverwrite: "Current cart is not empty — replace it with the parked cart?",
    scanCamera: "Scan with camera",
    scanCameraHint: "Point at a barcode — or use a hardware scanner / type the code",
    cameraPermissionDenied: "Camera permission denied",
    cameraUnsupported: "Camera is not supported on this device",
    approvals: "Approvals",
    approvalsTitle: "Approval requests",
    approvalsHint: "Sensitive POS approvals — valid for 15 minutes",
    approvalsEmpty: "No pending requests",
    approvalsFail: "Could not load approvals",
    approvalsManagerOnly: "Managers only",
    approve: "Approve",
    reject: "Reject",
    approveOk: "Approved",
    rejectOk: "Rejected",
    expiresAt: "Expires",
    shifts: "Shift",
    shiftsTitle: "Cash drawer shifts",
    shiftsHint: "Open a shift before selling — close it for a Z-report",
    shiftOpen: "Shift open",
    shiftClosed: "Shift closed",
    shiftClosedLabel: "Closed",
    shiftOpened: "Shift opened",
    shiftFail: "Could not complete shift action",
    noOpenShift: "No open shift",
    openShift: "Open shift",
    closeShift: "Close + Z-report",
    openingFloat: "Opening float",
    closingCash: "Counted closing cash",
    openedBy: "Opened by",
    shiftHistory: "Shift history",
    noShiftHistory: "No history yet",
    zSales: "Sales total",
    zCash: "Cash",
    zExpected: "Expected cash",
    zRefunds: "Refunds",
    zVoids: "Voids",
    zCount: "Transactions",
    zVariance: "Variance",
    cashSales: "Cash",
    cardSales: "Card",
    expectedInDrawer: "Expected in drawer",
    shortage: "Shortage",
    overage: "Overage",
    balanced: "Balanced",
    reconciliationTitle: "Drawer reconciliation",
    countedCash: "Counted cash",
    difference: "Difference",
    aiReview: "Smart review",
    aiReviewOk: "No anomalies",
    aiReviewFail: "Smart review failed",
    aiReviewTitle: "Shift review",
    refundSale: "Refund",
    refundOk: "Refund completed",
    refundFail: "Refund failed",
    refundTitle: "Partial refund",
    refundReason: "Refund reason",
    refundQty: "Refund qty",
    refundSelect: "Pick lines and quantities",
    refundContinue: "Continue to approval",
    printZReport: "Print Z-report",
    xReport: "X-report",
    printXReport: "Print X-report",
    xReportFail: "Could not load X-report",
    cashIn: "Cash in",
    cashOut: "Cash out",
    cashInOk: "Cash in recorded",
    cashOutOk: "Cash out recorded",
    cashMovementFail: "Could not record cash movement",
    cashMovementAmount: "Amount",
    cashMovementReason: "Reason (optional)",
    cashMovementReasonRequired: "Reason (required for cash out)",
    cashMovements: "Cash movements",
    noCashMovements: "No cash movements yet",
    cashPostedToGl: "Posted to GL",
    shiftsTodayTitle: "Today's shifts",
    shiftsTodayHint: "All warehouses — sales and expected cash",
    shiftsTodayEmpty: "No shifts today",
    shiftStatusOpen: "Open",
    shiftStatusClosed: "Closed",
    stockExceedsBlock: "Cart qty exceeds on-hand stock — adjust before paying",
    stockLowAfterSale: "Stock will fall to/below the low threshold after this sale. Continue?",
    zCashIn: "Cash in",
    zCashOut: "Cash out",
    shareReportWhatsApp: "Share WhatsApp",
    shareReportEmail: "Share email",
    recentPurchases: "Recent purchases",
    noRecentPurchases: "No recent purchases",
    addCustomer: "Add customer",
    customerName: "Customer name",
    customerPhone: "Customer phone",
    phoneRequired: "Phone number is required",
    phoneCountryCode: "Country code",
    phoneLocal: "Mobile number",
    phonePreview: "Preview",
    customerEmail: "Email (optional)",
    customerSaved: "Customer saved",
    catalogStale: "Catalog is stale — refresh when online",
    refreshCatalog: "Refresh catalog",
    lowStock: "Low stock",
    openDrawer: "Open drawer",
    preferCashDrawer: "Auto-open cash drawer after cash payment",
    todaySales: "Today's sales",
    shiftStripOpen: "Shift open",
    shiftStripClosed: "No shift",
    requireOpenShift: "Require open shift before sale",
    requireOpenShiftToast: "Open a shift before completing a sale",
    openShiftsLink: "Open shifts",
    shareWhatsApp: "Share WhatsApp",
    shareEmail: "Share email",
    shareWhatsAppPdfPreparing: "Preparing PDF for WhatsApp…",
    shareWhatsAppPdfOk: "Receipt shared with PDF",
    shareWhatsAppPdfDownloaded: "PDF downloaded — attach it in WhatsApp",
    shareWhatsAppPdfFail: "Could not create WhatsApp PDF",
    partnerPay: "Partner pay (card/wallet)",
    partnerPayHint: "Opens Thawani/Stripe/PayPal — not the NFC approval badge",
    partnerPayOpened: "Partner checkout opened",
    partnerPayFail: "Could not open partner pay — enable a company gateway",
    partnerPayOffline: "Partner pay needs an online invoice",
    terminalTap: "Tap / Terminal",
    terminalTapHint: "SoftPOS or partner terminal — customer tap-to-pay (not approval badge)",
    terminalTapOpened: "Terminal tap session opened",
    terminalTapFail: "Could not start terminal session — check gateway / POS_TERMINAL_MODE",
    terminalTapOffline: "Terminal tap needs an online invoice",
    terminalTapMockOk: "Mock terminal tap confirmed",
    terminalTapPaid: "Terminal / partner payment received",
    partnerPayPending: "Invoice awaiting payment — watching session",
    opQueued: "Operation queued offline — will sync when online",
    offlineOpLocalOnly: "Cannot void/refund a local offline receipt before sync",
    muteScanBeep: "Mute scan beep",
    favorites: "Favorites",
    pinFavorite: "Pin favorite",
    unpinFavorite: "Unpin favorite",
    renameParked: "Rename",
    renameParkedPrompt: "Parked cart name",
    renameParkedOk: "Name updated",
    refundReasonDamaged: "Damaged",
    refundReasonWrongItem: "Wrong item",
    refundReasonCustomerReturn: "Customer return",
    refundReasonOther: "Other",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutEsc: "Esc — clear cart",
    shortcutScan: "Enter — scan / add from barcode field",
    shortcutHelp: "? — show this help",
    keypadOk: "OK",
    keypadClear: "C",
    tip: "Tip",
    tipPercent: "Tip %",
    tipCustom: "Custom",
    splitTender: "Split tender",
    splitCash: "Cash",
    splitCard: "Card",
    splitSumMismatch: "Payment amounts must equal the total",
    splitCheckout: "Complete split",
    parkNotes: "Cart notes",
    parkNotesPlaceholder: "Optional notes when parking…",
    editParkNotes: "Notes",
    commission: "Comm",
    commissionRemaining: "rem",
    commissionPaid: "paid",
    commissionEarned: "Earned",
    commissionToday: "Today commission",
    payout: "Payout",
    payoutOk: "Commission paid out",
    payoutFail: "Payout failed",
    payoutAmount: "Payout amount",
    points: "Points",
    incentivesTitle: "Commission & loyalty",
    incentivesDesc: "Cashier percent commission and customer points on sales",
    incentivesSaved: "Incentives settings saved",
    cashierCommissionEnabled: "Enable cashier commission",
    cashierPercent: "Commission %",
    customerLoyaltyEnabled: "Enable customer points",
    pointsPerUnit: "Points per currency unit",
    nextBonusTier: "Next tier",
    ledgerEmpty: "No ledger yet",
  },
} as const;
