export type PosLocale = "ar" | "en";

export const posCopy = {
  ar: {
    brand: "كاشير حسابي",
    brandEn: "Hisaby POS",
    tagline: "نقطة بيع عالمية للمحلات والمتاجر",
    loginTitle: "دخول الكاشير",
    loginSub: "سجّل الدخول لفتح شاشة البيع",
    email: "البريد",
    password: "كلمة المرور",
    signIn: "دخول",
    toAccounting: "المحاسبة",
    toPos: "الكاشير",
    settings: "الإعدادات والربط",
    logout: "خروج",
    scanPlaceholder: "امسح الباركود أو اكتب SKU ثم Enter",
    searchPlaceholder: "بحث سريع عن منتج…",
    cart: "السلة",
    emptyCart: "السلة فارغة — ابدأ بالمسح",
    qty: "الكمية",
    price: "السعر",
    total: "الإجمالي",
    subtotal: "المجموع",
    tax: "الضريبة",
    payCash: "نقدًا",
    payCard: "بطاقة",
    payBank: "تحويل بنكي",
    clear: "تفريغ",
    parkCart: "تعليق",
    recallCart: "استرجاع",
    parkedCarts: "سلات معلّقة",
    parkOk: "تم تعليق السلة",
    parkFail: "فشل تعليق السلة",
    parkEmpty: "السلة فارغة",
    deleteParked: "حذف",
    parkName: "سلة معلّقة",
    stock: "المخزون",
    discount: "خصم",
    linked: "النظامان مربوطان",
    unlinked:
      "النظامان غير مربوطين — سجّل الدخول بنفس حساب المحاسبة أو فعّل الربط من الإعدادات",
    activateLink: "ربط عبر تسجيل الدخول",
    generateKey: "إنشاء مفتاح تقني",
    pasteKey: "لصق مفتاح الربط",
    saveKey: "تأكيد الربط",
    keyHint: "احفظ المفتاح الآن — لن يظهر مرة أخرى",
    saleOk: "تم البيع بنجاح",
    saleFail: "فشل إتمام البيع",
    notFound: "لا يوجد منتج بهذا الرمز",
    printReceipt: "طباعة إيصال",
    openPos: "فتح الكاشير",
    openAccounting: "فتح المحاسبة",
    chooseProduct: "اختر نظامك",
    chooseSub: "منصتان منفصلتان — محاسبية وكاشير — مع ربط اختياري",
    accountingCard: "حسابي للمحاسبة",
    accountingDesc: "فواتير، مخزون، تقارير، وضريبة القيمة المضافة",
    posCard: "حسابي للكاشير",
    posDesc: "بيع سريع، باركود، وخصم مخزون فوري للمحلات",
    emptyCatalog: "لا توجد منتجات للبيع بعد",
    emptyCatalogHint: "أضف منتجات من المخزون ثم ارجع للكاشير — يُفضّل تعبئة الباركود لكل صنف",
    goInventory: "الذهاب للمخزون",
    barcodeHint: "ضع المؤشر هنا وامسح بالقارئ — يعمل مع الباركود أو رمز SKU",
    inventory: "المخزون",
    posLinkTitle: "ربط حسابي للكاشير",
    posLinkDesc: "فعّل الربط أو أنشئ مفتاحاً تقنياً لربط الكاشير بالمحاسبة",
    warehouse: "المستودع",
    warehouseDefault: "المستودع",
    warehouseAll: "اختر مستودعاً",
    warehouseHint: "الرصيد المعروض لهذا المستودع فقط — اختر المستودع قبل البيع",
    clearConfirm: "تفريغ السلة؟",
    recentSales: "آخر المبيعات",
    reprint: "إعادة طباعة",
    noRecentSales: "لا مبيعات كاشير حديثة",
    escHint: "Esc لتفريغ السلة",
    adminOnlyKeys: "إنشاء وتأكيد المفتاح التقني متاح للمدير فقط",
    forbidden: "ليس لديك صلاحية لهذا الإجراء",
    linkFail: "فشل الربط — تحقق من الصلاحية أو المفتاح",
    voidSale: "إلغاء",
    voidConfirm: "إلغاء هذا البيع واسترجاع المخزون؟",
    voidOk: "تم إلغاء البيع",
    voidFail: "فشل إلغاء البيع",
    walkIn: "عميل نقدي",
    customer: "العميل",
    payment: "الدفع",
    recallOverwrite: "السلة الحالية غير فارغة — استبدالها بالسلة المعلّقة؟",
    scanCamera: "مسح بالكاميرا",
    scanCameraHint: "وجّه الكاميرا للباركود — أو استخدم قارئ الأجهزة / اكتب الرمز",
    cameraPermissionDenied: "تم رفض إذن الكاميرا",
    cameraUnsupported: "الكاميرا غير مدعومة على هذا الجهاز",
    approvals: "الموافقات",
    approvalsTitle: "طلبات الموافقة",
    approvalsHint: "موافقات الكاشير الحساسة — صالح 15 دقيقة",
    approvalsEmpty: "لا طلبات معلّقة",
    approvalsFail: "تعذر تحميل الموافقات",
    approvalsManagerOnly: "هذه الصفحة للمدير فقط",
    approve: "موافقة",
    reject: "رفض",
    approveOk: "تمت الموافقة",
    rejectOk: "تم الرفض",
    expiresAt: "ينتهي",
  },
  en: {
    brand: "Hisaby POS",
    brandEn: "كاشير حسابي",
    tagline: "World-class point of sale for retail stores",
    loginTitle: "POS sign in",
    loginSub: "Sign in to open the checkout floor",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    toAccounting: "Accounting",
    toPos: "POS",
    settings: "Settings & link",
    logout: "Sign out",
    scanPlaceholder: "Scan barcode or type SKU, then Enter",
    searchPlaceholder: "Quick product search…",
    cart: "Cart",
    emptyCart: "Cart is empty — start scanning",
    qty: "Qty",
    price: "Price",
    total: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    payCash: "Cash",
    payCard: "Card",
    payBank: "Bank transfer",
    clear: "Clear",
    parkCart: "Park",
    recallCart: "Recall",
    parkedCarts: "Parked carts",
    parkOk: "Cart parked",
    parkFail: "Could not park cart",
    parkEmpty: "Cart is empty",
    deleteParked: "Delete",
    parkName: "Parked cart",
    stock: "Stock",
    discount: "Discount",
    linked: "Apps are linked",
    unlinked:
      "Apps are not linked — sign in with the same accounting account or enable linking in settings",
    activateLink: "Link via shared login",
    generateKey: "Generate technical key",
    pasteKey: "Paste integration key",
    saveKey: "Confirm link",
    keyHint: "Store this key now — it will not be shown again",
    saleOk: "Sale completed",
    saleFail: "Sale failed",
    notFound: "No product for this code",
    printReceipt: "Print receipt",
    openPos: "Open POS",
    openAccounting: "Open Accounting",
    chooseProduct: "Choose your system",
    chooseSub: "Two separate products — accounting and POS — with optional linking",
    accountingCard: "Hisaby Accounting",
    accountingDesc: "Invoices, inventory, reports, and VAT",
    posCard: "Hisaby POS",
    posDesc: "Fast checkout, barcodes, and instant stock for stores",
    emptyCatalog: "No products to sell yet",
    emptyCatalogHint: "Add products in Inventory, then return here — barcodes make scanning fastest",
    goInventory: "Go to inventory",
    barcodeHint: "Keep focus here and scan — accepts barcode or SKU",
    inventory: "Inventory",
    posLinkTitle: "Hisaby POS link",
    posLinkDesc: "Activate linking or generate a technical key to connect POS with Accounting",
    warehouse: "Warehouse",
    warehouseDefault: "Warehouse",
    warehouseAll: "Select warehouse",
    warehouseHint: "Shown stock is for the selected warehouse only — pick a warehouse before selling",
    clearConfirm: "Clear the cart?",
    recentSales: "Recent sales",
    reprint: "Reprint",
    noRecentSales: "No recent POS sales",
    escHint: "Esc clears cart",
    adminOnlyKeys: "Only admins can generate or confirm the technical key",
    forbidden: "You do not have permission for this action",
    linkFail: "Link failed — check permissions or the key",
    voidSale: "Void",
    voidConfirm: "Void this sale and restore stock?",
    voidOk: "Sale voided",
    voidFail: "Could not void sale",
    walkIn: "Walk-in",
    customer: "Customer",
    payment: "Payment",
    recallOverwrite: "Current cart is not empty — replace it with the parked cart?",
    scanCamera: "Scan with camera",
    scanCameraHint: "Point at a barcode — or use a hardware scanner / type the code",
    cameraPermissionDenied: "Camera permission denied",
    cameraUnsupported: "Camera is not supported on this device",
    approvals: "Approvals",
    approvalsTitle: "Approval requests",
    approvalsHint: "Sensitive POS approvals — valid for 15 minutes",
    approvalsEmpty: "No pending requests",
    approvalsFail: "Could not load approvals",
    approvalsManagerOnly: "Managers only",
    approve: "Approve",
    reject: "Reject",
    approveOk: "Approved",
    rejectOk: "Rejected",
    expiresAt: "Expires",
  },
} as const;
