export type RestoLocale = "ar" | "en";

export const restoCopy = {
  ar: {
    brand: "حسابي للمطاعم",
    tagline: "صالة · مطبخ · قائمة",
    loginTitle: "دخول المطاعم",
    loginSub: "نفس حساب شركتك في حسابي",
    signIn: "تسجيل الدخول",
    email: "البريد",
    password: "كلمة المرور",
    floor: "الصالة",
    menu: "القائمة",
    settings: "الإعدادات",
    toAccounting: "المحاسبة",
    toPos: "الكاشير",
    logout: "خروج",
    floorEmptyTitle: "الصالة جاهزة للتهيئة",
    floorEmptyBody:
      "مخطط الطاولات والمناطق يصل في الموجة التالية (R2). يمكنك الآن ربط الشركة ومراجعة قائمة الأصناف.",
    menuTitle: "قائمة الأصناف",
    menuSub: "منتجات الشركة النشطة — مصدر القائمة في الموجة الأولى",
    menuSearch: "بحث بالاسم أو الرمز…",
    menuEmpty: "لا توجد منتجات نشطة. أضف أصنافاً من المخزون في المحاسبة أو الكاشير.",
    menuCount: "صنف",
    linkBanner: "المطاعم غير مربوطة بالمحاسبة بعد — فعّل الربط من الإعدادات.",
    linkTitle: "ربط حسابي للمطاعم",
    linkDesc:
      "اربط نظام المطاعم بنفس شركتك في المحاسبة والكاشير لمشاركة المنتجات والدفع لاحقاً.",
    linked: "مربوط",
    notLinked: "غير مربوط",
    activateLink: "تفعيل الربط الآن",
    unlink: "فك الربط",
    unlinkConfirm: "فك ربط المطاعم عن هذه الشركة؟",
    unlinkOk: "تم فك الربط",
    unlinkFail: "تعذر فك الربط",
    linkFail: "تعذر الربط",
    generateKey: "توليد مفتاح تقني",
    keyHint: "احفظ المفتاح الآن — لن يُعرض مجدداً",
    pasteKey: "الصق مفتاح hresto_…",
    confirmKey: "تأكيد بالمفتاح",
    copy: "نسخ",
    forbidden: "غير مسموح لهذه الصلاحية",
    openResto: "فتح المطاعم",
    comingR2: "الطاولات والطلبات المفتوحة في R2",
    price: "السعر",
    category: "التصنيف",
  },
  en: {
    brand: "Hisaby Restaurants",
    tagline: "Floor · Kitchen · Menu",
    loginTitle: "Restaurant sign-in",
    loginSub: "Same Hisaby company account",
    signIn: "Sign in",
    email: "Email",
    password: "Password",
    floor: "Floor",
    menu: "Menu",
    settings: "Settings",
    toAccounting: "Accounting",
    toPos: "POS",
    logout: "Log out",
    floorEmptyTitle: "Floor ready for setup",
    floorEmptyBody:
      "Tables and zones arrive in wave R2. You can link the company and review the menu now.",
    menuTitle: "Menu items",
    menuSub: "Active company products — menu source for wave R1",
    menuSearch: "Search name or code…",
    menuEmpty: "No active products. Add items from Accounting or POS inventory.",
    menuCount: "items",
    linkBanner: "Restaurants are not linked yet — activate linking in Settings.",
    linkTitle: "Link Hisaby Restaurants",
    linkDesc:
      "Bind restaurants to the same company as Accounting and POS to share products and future payments.",
    linked: "Linked",
    notLinked: "Not linked",
    activateLink: "Activate link now",
    unlink: "Unlink",
    unlinkConfirm: "Unlink restaurants from this company?",
    unlinkOk: "Unlinked",
    unlinkFail: "Could not unlink",
    linkFail: "Could not link",
    generateKey: "Generate technical key",
    keyHint: "Save this key now — it will not be shown again",
    pasteKey: "Paste hresto_… key",
    confirmKey: "Confirm with key",
    copy: "Copy",
    forbidden: "Not allowed for this role",
    openResto: "Open restaurants",
    comingR2: "Tables and open tickets in R2",
    price: "Price",
    category: "Category",
  },
} as const;
