export type RestoLocale = "ar" | "en";

export const restoCopy = {
  ar: {
    brand: "حسابي للمطاعم",
    tagline: "صالة · مطبخ · قائمة",
    loginTitle: "دخول المطاعم",
    loginSub: "نفس حساب شركتك في حسابي",
    signIn: "تسجيل الدخول",
    email: "البريد",
    password: "كلمة المرور",
    floor: "الصالة",
    menu: "القائمة",
    kitchen: "المطبخ",
    reports: "التقارير",
    reservations: "الحجوزات",
    settings: "الإعدادات",
    toAccounting: "المحاسبة",
    toPos: "الكاشير",
    logout: "خروج",
    openRestoShort: "المطاعم",
    floorEmptyTitle: "لا توجد طاولات بعد",
    floorEmptyBody:
      "أنشئ صالة تجريبية بثماني طاولات للبدء فوراً، أو أضف منطقة وطاولة من الإعدادات لاحقاً.",
    seedFloor: "تهيئة صالة تجريبية",
    seeding: "جاري التهيئة…",
    menuTitle: "قائمة الأصناف",
    menuSub: "منتجات الشركة النشطة — مصدر الطلبات",
    menuSearch: "بحث بالاسم أو الرمز…",
    menuEmpty: "لا أصناف في مخزن المطاعم. اربط مخزناً قطاعه «مطاعم» وانقل/عيّن أصناف الوجبات إليه.",
    menuCount: "صنف",
    linkBanner: "المطاعم غير مربوطة أو بلا مخزن — اختر مخزن المطاعم من الإعدادات.",
    linkTitle: "ربط حسابي للمطاعم",
    linkDesc:
      "اربط المطاعم بمخزن/فرع خاص بالوجبات فقط — القائمة لا تجلب كل أصناف الشركة.",
    linked: "مربوط",
    notLinked: "غير مربوط",
    activateLink: "تفعيل الربط الآن",
    warehouseLabel: "مخزن المطاعم",
    warehouseHint: "يظهر في القائمة فقط ما هو معيّن أو مخزّن في هذا المخزن",
    warehouseSave: "حفظ المخزن",
    warehouseRequired: "اختر مخزن المطاعم أولاً",
    warehouseSaved: "تم ربط المخزن",
    needsWarehouse: "اختر مخزن المطاعم لعرض القائمة",
    unlink: "فك الربط",
    unlinkConfirm: "فك ربط المطاعم عن هذه الشركة؟",
    unlinkOk: "تم فك الربط",
    unlinkFail: "تعذر فك الربط",
    linkFail: "تعذر الربط",
    generateKey: "توليد مفتاح تقني",
    keyHint: "احفظ المفتاح الآن — لن يُعرض مجدداً",
    pasteKey: "الصق مفتاح hresto_…",
    confirmKey: "تأكيد بالمفتاح",
    copy: "نسخ",
    forbidden: "غير مسموح لهذه الصلاحية",
    openResto: "فتح المطاعم",
    price: "السعر",
    category: "التصنيف",
    free: "فارغة",
    occupied: "مشغولة",
    billing: "حساب",
    reserved: "محجوزة",
    openOrder: "فتح طلب",
    viewOrder: "عرض الطلب",
    guests: "الضيوف",
    addItems: "إضافة أصناف",
    sendKitchen: "إرسال للمطبخ",
    closeOrder: "إغلاق الطلب",
    closeConfirm: "إغلاق تشغيلي بدون فاتورة؟ تتحرر الطاولة دون أثر محاسبي.",
    closeOk: "أُغلق الطلب",
    sendOk: "أُرسل للمطبخ",
    orderTotal: "الإجمالي",
    subtotal: "المجموع",
    pending: "بالانتظار",
    sent: "أُرسل",
    preparing: "قيد التحضير",
    ready: "جاهز",
    served: "قُدّم",
    cancelled: "ملغى",
    partial: "جزئي",
    closed: "مغلق",
    open: "مفتوح",
    noItems: "لا أصناف بعد — اختر من القائمة",
    remove: "حذف",
    kitchenTitle: "شاشة المطبخ",
    kitchenSub: "طلبات قيد التحضير — حدّث الحالة فور الجاهزية",
    kitchenEmpty: "لا طلبات في المطبخ حالياً",
    markPreparing: "تحضير",
    kdsFilterAll: "الكل",
    kdsSoundOn: "تنبيه صوتي",
    kdsBumpHint: "اختصار: B لترحيل أقدم جاهز → مُسلَّم",
    itemNotes: "ملاحظة للمطبخ",
    itemNotesPh: "بدون بصل، حار…",
    printCheck: "طباعة فاتورة الضيف",
    tipAmount: "بقشيش",
    tipAssignee: "مستلم البقشيش",
    tipAssigneeHint: "النادل الذي يُنسب إليه البقشيش في التقارير",
    sectionStaff: "توزيع النُدُل على المناطق",
    sectionStaffSub: "عيّن نادلاً لكل منطقة — يظهر على الأرضية ويُقترح عند الإغلاق",
    sectionUnassigned: "غير معيّن",
    sectionAssign: "تعيين",
    sectionRelease: "إلغاء التعيين",
    sectionServer: "نادل المنطقة",
    flashPrint: "طباعة Flash",
    flashTitle: "تقرير Flash — يوم العمل",
    flashPrinted: "طُبع في",
    flashSections: "توزيع المناطق الآن",
    guestsEdit: "عدد الضيوف",
    qty: "الكمية",
    markReady: "جاهز",
    transferTable: "نقل طاولة",
    mergeOrder: "دمج طلب",
    splitOrder: "تقسيم",
    splitHint: "اختر أصنافاً ثم قسّم لطاولة فارغة أو سفري",
    pickFreeTable: "طاولة فارغة",
    pickTargetOrder: "طلب الهدف",
    confirmTransfer: "تأكيد النقل",
    confirmMerge: "تأكيد الدمج",
    confirmSplit: "تأكيد التقسيم",
    splitTakeaway: "تقسيم لسفري",
    modifiers: "إضافات",
    delivery: "توصيل",
    deliveryTitle: "طلبات التوصيل",
    deliverySub: "قناة التوصيل — افتح طلباً أو أكمل من هنا",
    deliveryEmpty: "لا طلبات توصيل مفتوحة",
    deliveryOpen: "توصيل جديد",
    kdsLive: "بث مباشر",
    opsTitle: "عمليات الطاولة",
    course: "كورس",
    courseDrinks: "مشروبات",
    courseStarter: "مقبلات",
    courseMain: "أطباق رئيسية",
    courseDessert: "حلويات",
    fireCourse: "إطلاق للمطبخ",
    fireAll: "إرسال الكل",
    waitlist: "قائمة الانتظار",
    waitlistTitle: "قائمة انتظار الضيوف",
    waitlistSub: "ضيوف بلا طاولة — أشعرهم أو أجْلِسهم على طاولة فارغة",
    waitlistEmpty: "لا أحد في الانتظار",
    waitlistAdd: "إضافة للانتظار",
    waitlistNotify: "إشعار",
    waitlistSeat: "إجلاس",
    waitlistCancel: "إلغاء",
    waitedMin: "دقيقة انتظار",
    quotedMin: "وقت متوقع (د)",
    menu86: "غير متوفر (86)",
    menu86Title: "أصناف غير متوفرة",
    menu86Sub: "إخفاء أصناف نفدت — تلقائي من المخزون أو يدوي",
    menu86Empty: "لا أصناف معلّمة 86",
    menu86Mark: "تعليم 86",
    menu86Clear: "إعادة التوفر",
    menu86Auto: "تلقائي",
    menu86Manual: "يدوي",
    menu86Reconcile: "مزامنة المخزون ← 86",
    menu86ReconcileOk: "تم تحديث التوفر من المخزون",
    pickTableSeat: "طاولة للإجلاس",
    voidItem: "إلغاء بند",
    guestQr: "QR للضيف",
    guestQrTitle: "روابط طلب الضيف (QR)",
    guestQrHint: "اطبع أو اعرض الرابط على الطاولة — الضيف يطلب من جواله",
    guestQrEnsure: "توليد روابط كل الطاولات",
    guestQrCopy: "نسخ الرابط",
    guestQrCopied: "تم النسخ",
    guestCall: "استدعاء ضيف",
    guestCallClear: "تم الرد",
    guestCallWaiter: "نادل",
    guestCallCheck: "فاتورة",
    guestCallWater: "ماء",
    qrPrintTitle: "طباعة بطاقات QR للطاولات",
    qrPrintSub: "بطاقة لكل طاولة — اطبعها وضَعها على الطاولة",
    qrPrintBtn: "طباعة",
    qrPrintScan: "امسح للطلب من جوالك",
    qrPrintOpen: "فتح صفحة الطباعة",
    occupiedMin: "دقيقة شغل",
    guestOrderBadge: "طلب ضيف",
    fromGuest: "ضيف",
    kitchenTicket: "تذكرة مطبخ",
    compItem: "مجاملة (كمب)",
    voidReasonPh: "سبب الإلغاء / المجاملة…",
    voidOk: "تم الإلغاء",
    compOk: "تم تسجيل المجاملة",
    allergens: "مسببات الحساسية",
    allergensHint: "اختر مسببات الحساسية في الصنف",
    allergenFilter: "أخفِ ما يحتوي",
    dietary: "وسوم غذائية",
    dietaryHint: "حلال، نباتي، حار…",
    dietaryFilter: "يحتوي على",
    dayParts: "فترات اليوم",
    dayPartsHint: "فارغ = متاح طوال اليوم",
    dayPartAll: "طوال اليوم",
    dayPartBreakfast: "فطور",
    dayPartLunch: "غداء",
    dayPartDinner: "عشاء",
    dayPartLate: "ليلي",
    dayPartNow: "الفترة الحالية",
    coursePick: "الدورة",
    lineNotes: "ملاحظة للمطبخ",
    serviceCharge: "رسوم خدمة",
    serviceChargePct: "خدمة %",
    expo: "التقديم",
    expoTitle: "شاشة التقديم (Expo)",
    expoSub: "أصناف جاهزة بانتظار التقديم للطاولة أو التوصيل",
    expoEmpty: "لا أصناف جاهزة للتقديم",
    expoServe: "قُدّم",
    guestPhone: "هاتف الضيف",
    deliveryAddress: "عنوان التوصيل",
    deliveryQueued: "بالانتظار",
    deliveryKitchen: "المطبخ",
    deliveryReady: "جاهز",
    deliveryOut: "في الطريق",
    deliveryDelivered: "تم التسليم",
    deliveryDispatch: "إرسال مع السائق",
    driverName: "اسم السائق",
    driverPhone: "هاتف السائق",
    markServed: "قُدّم",
    table: "طاولة",
    order: "طلب",
    refresh: "تحديث",
    seats: "مقاعد",
    notes: "ملاحظات",
    closeHint: "الإغلاق الافتراضي ينشئ فاتورة محاسبة. استخدم الإغلاق التشغيلي بدون فوترة عند الحاجة.",
    actionFail: "تعذر تنفيذ العملية",
    fail: "تعذر تنفيذ العملية",
    takeaway: "سفري",
    takeawayTitle: "طلبات السفري",
    takeawaySub: "طلبات بدون طاولة — افتح أو أكمل الإغلاق من هنا",
    takeawayEmpty: "لا طلبات سفري مفتوحة",
    takeawayOpen: "سفري جديد",
    kitchenSound: "تنبيه صوتي للطلبات الجديدة",
    payCash: "إغلاق ودفع نقداً",
    payCard: "إغلاق وبطاقة",
    paySplit: "دفع مقسّم",
    payLink: "رابط دفع أونلاين",
    payLinkOk: "تم إنشاء رابط الدفع",
    cashPart: "نقداً",
    cardPart: "بطاقة (الباقي)",
    softClose: "إغلاق تشغيلي فقط",
    closePaidHint: "يُنشئ فاتورة في الكاشير/المحاسبة ويخصم المخزون",
    paymentMethod: "طريقة الدفع",
    cash: "نقداً",
    card: "بطاقة",
    closePaidOk: "أُغلق الطلب وفُوتر",
    cancelOrder: "إلغاء الطلب",
    cancelConfirm: "إلغاء الطلب وتحرير الطاولة؟ لا يمكن التراجع.",
    cancelOk: "أُلغي الطلب",
    allStations: "كل المحطات",
    stations: "محطات المطبخ",
    stationsHint: "أضف محطات مثل المطبخ والبار لتصفية شاشة التحضير",
    addStation: "إضافة محطة",
    stationName: "اسم المحطة",
    stationAdded: "أُضيفت المحطة",
    toStation: "إلى محطة",
    stationAuto: "تلقائي (حسب الصنف)",
    reservationsSub: "حجوزات الطاولات لليوم والأيام القادمة",
    reservationsEmpty: "لا حجوزات في الأيام القادمة",
    addReservation: "إضافة حجز",
    reservationOk: "تم الحجز",
    guestName: "اسم الضيف",
    phone: "الهاتف",
    tableOptional: "طاولة (اختياري)",
    resPending: "بانتظار",
    resConfirmed: "مؤكد",
    resSeated: "جالس",
    resNoShow: "لم يحضر",
    resConfirm: "تأكيد",
    resSeat: "إجلاس",
    recipes: "الوصفات",
    recipesTitle: "وصفات المطبخ",
    recipesSub: "مكونات لكل طبق — تُخصم عند الإغلاق المدفوع إذا كان الطبق غير متتبَّع في المخزون",
    recipesEmpty: "لا وصفات بعد — اختر طبقاً وأضف مكوناته",
    recipeDish: "الطبق",
    recipeComponent: "المكوّن",
    recipeQty: "الكمية لكل وحدة",
    addComponent: "إضافة مكوّن",
    saveRecipe: "حفظ الوصفة",
    deleteRecipe: "حذف الوصفة",
    recipeSaved: "حُفظت الوصفة",
    recipeDeleted: "حُذفت الوصفة",
    recipeTrackedWarn: "الطبق متتبَّع مخزنياً — عند الإغلاق يُخصم الطبق نفسه وليس المكونات",
    recipeUntrackedOk: "الطبق غير متتبَّع — عند الإغلاق تُخصم المكونات فقط",
    demoSeedTitle: "بيانات تجريبية متعددة الفروع",
    demoSeedHint:
      "يفتح 3 فروع (مطعم · مقهى · بقالة) مع مخازن ووجبات بصور وسلع — قابلة للتعديل والحذف (SKU يبدأ بـ DEMO-)",
    demoSeedRun: "تعبئة بيانات تجريبية",
    demoSeedOk: "تمت تعبئة البيانات التجريبية",
    demoPurge: "حذف البيانات التجريبية فقط",
    demoPurgeConfirm: "حذف كل فروع/مخازن/أصناف DEMO-؟",
    demoPurgeOk: "حُذفت البيانات التجريبية",
    editInInventory: "تعديل في المخزون",
    reportsTitle: "تقارير المطاعم",
    reportsSub: "مؤشرات تشغيلية عالمية — إيراد، دورة طاولة، تحضير، إلغاءات",
    reportOrders: "طلبات",
    reportClosed: "مغلقة",
    reportCancelled: "ملغاة",
    reportRevenue: "إيراد تشغيلي",
    reportAvgPrep: "متوسط التحضير (د)",
    reportPrepP90: "تحضير P90 (د)",
    reportAvgTicket: "متوسط الفاتورة",
    reportTurn: "دورة الطاولة (د)",
    reportVoidRate: "نسبة الإلغاء %",
    reportCompRate: "نسبة المجاملة %",
    reportTips: "إجمالي البقشيش",
    reportAvgTip: "متوسط البقشيش",
    reportServiceCharges: "رسوم الخدمة",
    reportTipPool: "حصة متساوية (تجميع)",
    reportByServer: "البقشيش حسب النادل",
    reportOpenNow: "طلبات مفتوحة الآن",
    reportTopItems: "الأصناف الأعلى",
    reportByTable: "حسب الطاولة",
    reportByHour: "حسب الساعة",
    reportByHourRev: "إيراد بالساعة",
    reportStationPrep: "تحضير حسب المحطة",
    reportVoidReasons: "أسباب الإلغاء",
    reportTurnCol: "دورة (د)",
    reportEmpty: "لا بيانات في الفترة المحددة",
    today: "اليوم",
    last7: "آخر 7 أيام",
    last30: "آخر 30 يوماً",
    overdue: "متأخر",
    kdsAllergens: "حساسية",
  },
  en: {
    brand: "Hisaby Restaurants",
    tagline: "Floor · Kitchen · Menu",
    loginTitle: "Restaurant sign-in",
    loginSub: "Same Hisaby company account",
    signIn: "Sign in",
    email: "Email",
    password: "Password",
    floor: "Floor",
    menu: "Menu",
    kitchen: "Kitchen",
    reports: "Reports",
    reservations: "Reservations",
    settings: "Settings",
    toAccounting: "Accounting",
    toPos: "POS",
    logout: "Log out",
    openRestoShort: "Restaurants",
    floorEmptyTitle: "No tables yet",
    floorEmptyBody:
      "Seed a demo hall with eight tables to start, or add zones and tables later.",
    seedFloor: "Seed demo floor",
    seeding: "Seeding…",
    menuTitle: "Menu items",
    menuSub: "Active company products — order source",
    menuSearch: "Search name or code…",
    menuEmpty: "No items in the restaurant warehouse. Bind a RESTAURANT-sector warehouse and assign meal products to it.",
    menuCount: "items",
    linkBanner: "Restaurants not linked or missing warehouse — pick a warehouse in Settings.",
    linkTitle: "Link Hisaby Restaurants",
    linkDesc:
      "Bind restaurants to a meal-only warehouse/branch — the menu will not pull the full company catalog.",
    linked: "Linked",
    notLinked: "Not linked",
    activateLink: "Activate link now",
    warehouseLabel: "Restaurant warehouse",
    warehouseHint: "Menu shows only products assigned or stocked in this warehouse",
    warehouseSave: "Save warehouse",
    warehouseRequired: "Select a restaurant warehouse first",
    warehouseSaved: "Warehouse linked",
    needsWarehouse: "Select a restaurant warehouse to show the menu",
    unlink: "Unlink",
    unlinkConfirm: "Unlink restaurants from this company?",
    unlinkOk: "Unlinked",
    unlinkFail: "Could not unlink",
    linkFail: "Could not link",
    generateKey: "Generate technical key",
    keyHint: "Save this key now — it will not be shown again",
    pasteKey: "Paste hresto_… key",
    confirmKey: "Confirm with key",
    copy: "Copy",
    forbidden: "Not allowed for this role",
    openResto: "Open restaurants",
    price: "Price",
    category: "Category",
    free: "Free",
    occupied: "Occupied",
    billing: "Billing",
    reserved: "Reserved",
    openOrder: "Open order",
    viewOrder: "View order",
    guests: "Guests",
    addItems: "Add items",
    sendKitchen: "Send to kitchen",
    closeOrder: "Close order",
    closeConfirm: "Soft-close without an invoice? Table frees with no accounting effect.",
    closeOk: "Order closed",
    sendOk: "Sent to kitchen",
    orderTotal: "Total",
    subtotal: "Subtotal",
    pending: "Pending",
    sent: "Sent",
    preparing: "Preparing",
    ready: "Ready",
    served: "Served",
    cancelled: "Cancelled",
    partial: "Partial",
    closed: "Closed",
    open: "Open",
    noItems: "No items yet — pick from the menu",
    remove: "Remove",
    kitchenTitle: "Kitchen display",
    kitchenSub: "Live tickets — update status as soon as ready",
    kitchenEmpty: "No kitchen tickets right now",
    markPreparing: "Prep",
    kdsFilterAll: "All",
    kdsSoundOn: "Sound alert",
    kdsBumpHint: "Shortcut: B bumps oldest Ready → Served",
    itemNotes: "Kitchen note",
    itemNotesPh: "No onion, spicy…",
    printCheck: "Print guest check",
    tipAmount: "Tip",
    tipAssignee: "Tip assignee",
    tipAssigneeHint: "Server credited for tips in reports",
    sectionStaff: "Section staffing",
    sectionStaffSub: "Assign a server to each zone — shown on floor and suggested at close",
    sectionUnassigned: "Unassigned",
    sectionAssign: "Assign",
    sectionRelease: "Release",
    sectionServer: "Section server",
    flashPrint: "Print flash",
    flashTitle: "Flash report — business day",
    flashPrinted: "Printed at",
    flashSections: "Active section staffing",
    guestsEdit: "Guests",
    qty: "Qty",
    markReady: "Ready",
    transferTable: "Transfer table",
    mergeOrder: "Merge check",
    splitOrder: "Split",
    splitHint: "Select lines, then split to a free table or takeaway",
    pickFreeTable: "Free table",
    pickTargetOrder: "Target order",
    confirmTransfer: "Confirm transfer",
    confirmMerge: "Confirm merge",
    confirmSplit: "Confirm split",
    splitTakeaway: "Split to takeaway",
    modifiers: "Modifiers",
    delivery: "Delivery",
    deliveryTitle: "Delivery orders",
    deliverySub: "Delivery channel — open or finish checks here",
    deliveryEmpty: "No open delivery orders",
    deliveryOpen: "New delivery",
    kdsLive: "Live stream",
    opsTitle: "Table ops",
    course: "Course",
    courseDrinks: "Drinks",
    courseStarter: "Starters",
    courseMain: "Mains",
    courseDessert: "Desserts",
    fireCourse: "Fire to kitchen",
    fireAll: "Send all",
    waitlist: "Waitlist",
    waitlistTitle: "Guest waitlist",
    waitlistSub: "Walk-ins without a table — notify or seat on a free table",
    waitlistEmpty: "No one waiting",
    waitlistAdd: "Add to waitlist",
    waitlistNotify: "Notify",
    waitlistSeat: "Seat",
    waitlistCancel: "Cancel",
    waitedMin: "min waited",
    quotedMin: "Quoted wait (min)",
    menu86: "86 board",
    menu86Title: "86'd items",
    menu86Sub: "Hide sold-out dishes — auto from stock or manual",
    menu86Empty: "No items marked 86",
    menu86Mark: "Mark 86",
    menu86Clear: "Make available",
    menu86Auto: "Auto",
    menu86Manual: "Manual",
    menu86Reconcile: "Sync stock → 86",
    menu86ReconcileOk: "Availability synced",
    pickTableSeat: "Table to seat",
    voidItem: "Void item",
    guestQr: "Guest QR",
    guestQrTitle: "Guest order QR links",
    guestQrHint: "Print or show the link on each table — guests order from their phone",
    guestQrEnsure: "Generate links for all tables",
    guestQrCopy: "Copy link",
    guestQrCopied: "Copied",
    guestCall: "Guest call",
    guestCallClear: "Ack",
    guestCallWaiter: "Waiter",
    guestCallCheck: "Check",
    guestCallWater: "Water",
    qrPrintTitle: "Print table QR cards",
    qrPrintSub: "One card per table — print and place on the table",
    qrPrintBtn: "Print",
    qrPrintScan: "Scan to order on your phone",
    qrPrintOpen: "Open print sheet",
    occupiedMin: "min seated",
    guestOrderBadge: "Guest order",
    fromGuest: "Guest",
    kitchenTicket: "Kitchen ticket",
    compItem: "Comp item",
    voidReasonPh: "Void / comp reason…",
    voidOk: "Item voided",
    compOk: "Item comped",
    allergens: "Allergens",
    allergensHint: "Mark allergens present in this dish",
    allergenFilter: "Hide items containing",
    dietary: "Dietary tags",
    dietaryHint: "Halal, vegan, spicy…",
    dietaryFilter: "Must include",
    dayParts: "Day parts",
    dayPartsHint: "Empty = available all day",
    dayPartAll: "All day",
    dayPartBreakfast: "Breakfast",
    dayPartLunch: "Lunch",
    dayPartDinner: "Dinner",
    dayPartLate: "Late night",
    dayPartNow: "Current day-part",
    coursePick: "Course",
    lineNotes: "Kitchen note",
    serviceCharge: "Service charge",
    serviceChargePct: "Service %",
    expo: "Expo",
    expoTitle: "Expo / runner pass",
    expoSub: "READY items waiting to be served to table or delivery",
    expoEmpty: "Nothing ready to run",
    expoServe: "Served",
    guestPhone: "Guest phone",
    deliveryAddress: "Delivery address",
    deliveryQueued: "Queued",
    deliveryKitchen: "Kitchen",
    deliveryReady: "Ready",
    deliveryOut: "Out for delivery",
    deliveryDelivered: "Delivered",
    deliveryDispatch: "Dispatch with driver",
    driverName: "Driver name",
    driverPhone: "Driver phone",
    markServed: "Served",
    table: "Table",
    order: "Order",
    refresh: "Refresh",
    seats: "seats",
    notes: "Notes",
    closeHint:
      "Default close creates an accounting invoice. Use soft close for table-only free without billing.",
    actionFail: "Action failed",
    fail: "Action failed",
    takeaway: "Takeaway",
    takeawayTitle: "Takeaway orders",
    takeawaySub: "Orders without a table — open or close from here",
    takeawayEmpty: "No open takeaway orders",
    takeawayOpen: "New takeaway",
    kitchenSound: "Sound alert for new tickets",
    payCash: "Close & pay cash",
    payCard: "Close & card",
    paySplit: "Split tender",
    payLink: "Online pay link",
    payLinkOk: "Pay link created",
    cashPart: "Cash",
    cardPart: "Card (remainder)",
    softClose: "Operational close only",
    closePaidHint: "Creates a POS/Accounting invoice and deducts stock",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    closePaidOk: "Order closed and invoiced",
    cancelOrder: "Cancel order",
    cancelConfirm: "Cancel this order and free the table? This cannot be undone.",
    cancelOk: "Order cancelled",
    allStations: "All stations",
    stations: "Kitchen stations",
    stationsHint: "Add stations like Kitchen and Bar to filter the KDS",
    addStation: "Add station",
    stationName: "Station name",
    stationAdded: "Station added",
    toStation: "Send to station",
    stationAuto: "Auto (by product)",
    reservationsSub: "Table bookings for today and the next days",
    reservationsEmpty: "No upcoming reservations",
    addReservation: "Add reservation",
    reservationOk: "Reservation saved",
    guestName: "Guest name",
    phone: "Phone",
    tableOptional: "Table (optional)",
    resPending: "Pending",
    resConfirmed: "Confirmed",
    resSeated: "Seated",
    resNoShow: "No-show",
    resConfirm: "Confirm",
    resSeat: "Seat",
    recipes: "Recipes",
    recipesTitle: "Kitchen recipes",
    recipesSub:
      "Ingredients per dish — deducted on paid close when the dish is not stock-tracked",
    recipesEmpty: "No recipes yet — pick a dish and add components",
    recipeDish: "Dish",
    recipeComponent: "Component",
    recipeQty: "Qty per unit",
    addComponent: "Add component",
    saveRecipe: "Save recipe",
    deleteRecipe: "Delete recipe",
    recipeSaved: "Recipe saved",
    recipeDeleted: "Recipe deleted",
    recipeTrackedWarn:
      "Dish is stock-tracked — close deducts the dish itself, not ingredients",
    recipeUntrackedOk:
      "Dish is not stock-tracked — close deducts ingredients only",
    demoSeedTitle: "Multi-branch demo data",
    demoSeedHint:
      "Creates 3 branches (restaurant · cafe · grocery) with warehouses, imaged meals, and retail SKUs — fully editable/deletable (SKU prefix DEMO-)",
    demoSeedRun: "Load demo catalog",
    demoSeedOk: "Demo catalog ready",
    demoPurge: "Delete demo data only",
    demoPurgeConfirm: "Delete all DEMO- branches/warehouses/products?",
    demoPurgeOk: "Demo data removed",
    editInInventory: "Edit in inventory",
    reportsTitle: "Restaurant reports",
    reportsSub: "Ops KPIs — revenue, table turn, prep, voids",
    reportOrders: "Orders",
    reportClosed: "Closed",
    reportCancelled: "Cancelled",
    reportRevenue: "Operating revenue",
    reportAvgPrep: "Avg prep (min)",
    reportPrepP90: "Prep P90 (min)",
    reportAvgTicket: "Avg ticket",
    reportTurn: "Table turn (min)",
    reportVoidRate: "Void rate %",
    reportCompRate: "Comp rate %",
    reportTips: "Tips total",
    reportAvgTip: "Avg tip",
    reportServiceCharges: "Service charges",
    reportTipPool: "Equal pool share",
    reportByServer: "Tips by server",
    reportOpenNow: "Open now",
    reportTopItems: "Top items",
    reportByTable: "By table",
    reportByHour: "By hour",
    reportByHourRev: "Revenue by hour",
    reportStationPrep: "Prep by station",
    reportVoidReasons: "Void reasons",
    reportTurnCol: "Turn (min)",
    reportEmpty: "No data in this period",
    today: "Today",
    last7: "Last 7 days",
    last30: "Last 30 days",
    overdue: "Late",
    kdsAllergens: "Allergens",
  },
} as const;
